# eBay : Industrial Robot Data fetching

In [1]:
import pandas as pd
from bs4 import BeautifulSoup

In [3]:
# Loading datasheets
search_terms = pd.read_excel("ebay_data_template (1).xlsx", sheet_name="Search Terms")
sold_data = pd.read_excel("ebay_data_template (1).xlsx", sheet_name="eBay Sold Data")

In [4]:
search_terms

,Search This Exact Phrase,OEM,Priority,Notes
0,FANUC robot,FANUC,HIGH,Main catch-all — covers most FANUC listings
1,FANUC LR Mate,FANUC,HIGH,"Small tabletop robots, high volume used"
2,FANUC M-20iA,FANUC,HIGH,Most common medium robot
3,FANUC M-20iD,FANUC,HIGH,Newer version of M-20
4,FANUC M-10iA,FANUC,HIGH,Medium payload workhorse
5,FANUC R-2000iC,FANUC,HIGH,Large palletizing robot
6,FANUC R-2000iA,FANUC,HIGH,"Older large robot, very common"
7,FANUC M-710iC,FANUC,HIGH,"Versatile medium-large, very common used"
8,FANUC M-900iA,FANUC,MEDIUM,Very large payload
9,FANUC M-900iB,FANUC,MEDIUM,"Very large payload, newer"
10,FANUC ARC Mate,FANUC,MEDIUM,Welding robots
11,FANUC R-30iB,FANUC,MEDIUM,Controller — catches listings titled by contro...
12,FANUC CR-7iA,FANUC,LOW,Collaborative robot
13,ABB robot arm,ABB,HIGH,Main catch-all for ABB
14,ABB IRB 6700,ABB,HIGH,"Large workhorse, very common"
15,ABB IRB 2600,ABB,HIGH,"Medium payload, widely used"
16,ABB IRB 4600,ABB,HIGH,Versatile medium-large
17,ABB IRB 1200,ABB,MEDIUM,Compact 6-axis
18,ABB IRB 6640,ABB,MEDIUM,"Older large robot, still common used"
19,ABB IRB 120,ABB,MEDIUM,Small tabletop
20,ABB IRC5 controller,ABB,LOW,Controller — catches listings titled by contro...
21,KUKA robot arm,KUKA,HIGH,Main catch-all for KUKA
22,KUKA KR 210,KUKA,HIGH,"Heavy payload, very common in automotive"
23,KUKA KR 150,KUKA,HIGH,"Medium-large, common used"
24,KUKA KR 16,KUKA,HIGH,Medium payload workhorse
25,KUKA KR 6,KUKA,MEDIUM,Small payload
26,KUKA KR 360,KUKA,MEDIUM,Very large payload
27,KUKA KR C4,KUKA,LOW,Controller — catches listings titled by contro...
28,Yaskawa robot,Yaskawa,HIGH,Main catch-all
29,Motoman robot,Yaskawa,HIGH,Yaskawa's robot brand name
30,Motoman HP20D,Yaskawa,HIGH,Very common medium robot
31,Motoman MH50,Yaskawa,MEDIUM,Medium-large payload
32,Motoman MA1440,Yaskawa,MEDIUM,Welding robot
33,Yaskawa DX200,Yaskawa,MEDIUM,Controller — catches controller listings
34,Motoman GP25,Yaskawa,LOW,Newer general purpose
35,Kawasaki robot arm,Kawasaki,MEDIUM,Main catch-all
36,Kawasaki RS006L,Kawasaki,MEDIUM,"Small-medium, common"
37,Kawasaki ZD130,Kawasaki,LOW,Palletizing robot
38,Kawasaki RS010L,Kawasaki,LOW,Medium payload
39,Universal Robots UR,Universal Robots,HIGH,Main catch-all for UR cobots
40,UR5 robot,Universal Robots,HIGH,Most popular cobot model
41,UR10 robot,Universal Robots,HIGH,Larger cobot
42,UR3 robot,Universal Robots,MEDIUM,Small tabletop cobot
43,UR5e robot,Universal Robots,MEDIUM,"E-series, newer"
44,UR10e robot,Universal Robots,MEDIUM,"E-series, newer"
45,UR16e robot,Universal Robots,LOW,Heavy-duty cobot
46,Epson robot SCARA,Epson,MEDIUM,SCARA robots for electronics/assembly
47,Epson T6 robot,Epson,LOW,6-axis compact
48,Denso robot arm,Denso,MEDIUM,"Compact robots, electronics/automotive"
49,Denso VS-6577,Denso,LOW,Common 6-axis model
50,Mitsubishi robot arm,Mitsubishi,MEDIUM,SCARA and articulated robots
51,Mitsubishi RV-7FL,Mitsubishi,LOW,Medium articulated
52,Staubli robot arm,Staubli,LOW,"Swiss precision robots, cleanroom"
53,Staubli TX60,Staubli,LOW,Common 6-axis model
54,Comau robot arm,Comau,LOW,"Italian, common in automotive"
55,Nachi robot arm,Nachi,LOW,"Japanese, welding and material handling"

### Sorting Search Terms By Priority

In [5]:
order = ["HIGH", "MEDIUM", "LOW"]
search_terms["Priority"] = pd.Categorical(search_terms["Priority"], categories=order, ordered=True)

In [6]:
search_terms = search_terms.sort_values("Priority", ignore_index=True)
search_terms

,Search This Exact Phrase,OEM,Priority,Notes
0,FANUC robot,FANUC,HIGH,Main catch-all — covers most FANUC listings
1,UR10 robot,Universal Robots,HIGH,Larger cobot
2,UR5 robot,Universal Robots,HIGH,Most popular cobot model
3,Universal Robots UR,Universal Robots,HIGH,Main catch-all for UR cobots
4,Motoman HP20D,Yaskawa,HIGH,Very common medium robot
5,Motoman robot,Yaskawa,HIGH,Yaskawa's robot brand name
6,Yaskawa robot,Yaskawa,HIGH,Main catch-all
7,KUKA KR 16,KUKA,HIGH,Medium payload workhorse
8,KUKA KR 210,KUKA,HIGH,"Heavy payload, very common in automotive"
9,KUKA robot arm,KUKA,HIGH,Main catch-all for KUKA
10,ABB IRB 4600,ABB,HIGH,Versatile medium-large
11,ABB IRB 2600,ABB,HIGH,"Medium payload, widely used"
12,ABB IRB 6700,ABB,HIGH,"Large workhorse, very common"
13,KUKA KR 150,KUKA,HIGH,"Medium-large, common used"
14,FANUC M-10iA,FANUC,HIGH,Medium payload workhorse
15,FANUC R-2000iA,FANUC,HIGH,"Older large robot, very common"
16,FANUC M-710iC,FANUC,HIGH,"Versatile medium-large, very common used"
17,FANUC R-2000iC,FANUC,HIGH,Large palletizing robot
18,FANUC M-20iD,FANUC,HIGH,Newer version of M-20
19,ABB robot arm,ABB,HIGH,Main catch-all for ABB
20,FANUC LR Mate,FANUC,HIGH,"Small tabletop robots, high volume used"
21,FANUC M-20iA,FANUC,HIGH,Most common medium robot
22,Denso robot arm,Denso,MEDIUM,"Compact robots, electronics/automotive"
23,UR3 robot,Universal Robots,MEDIUM,Small tabletop cobot
24,Kawasaki robot arm,Kawasaki,MEDIUM,Main catch-all
25,UR5e robot,Universal Robots,MEDIUM,"E-series, newer"
26,Mitsubishi robot arm,Mitsubishi,MEDIUM,SCARA and articulated robots
27,Yaskawa DX200,Yaskawa,MEDIUM,Controller — catches controller listings
28,Motoman MA1440,Yaskawa,MEDIUM,Welding robot
29,UR10e robot,Universal Robots,MEDIUM,"E-series, newer"
30,Kawasaki RS006L,Kawasaki,MEDIUM,"Small-medium, common"
31,Epson robot SCARA,Epson,MEDIUM,SCARA robots for electronics/assembly
32,KUKA KR 360,KUKA,MEDIUM,Very large payload
33,KUKA KR 6,KUKA,MEDIUM,Small payload
34,FANUC M-900iA,FANUC,MEDIUM,Very large payload
35,FANUC M-900iB,FANUC,MEDIUM,"Very large payload, newer"
36,ABB IRB 120,ABB,MEDIUM,Small tabletop
37,ABB IRB 6640,ABB,MEDIUM,"Older large robot, still common used"
38,ABB IRB 1200,ABB,MEDIUM,Compact 6-axis
39,FANUC ARC Mate,FANUC,MEDIUM,Welding robots
40,FANUC R-30iB,FANUC,MEDIUM,Controller — catches listings titled by contro...
41,Motoman MH50,Yaskawa,MEDIUM,Medium-large payload
42,Mitsubishi RV-7FL,Mitsubishi,LOW,Medium articulated
43,Epson T6 robot,Epson,LOW,6-axis compact
44,Denso VS-6577,Denso,LOW,Common 6-axis model
45,Staubli robot arm,Staubli,LOW,"Swiss precision robots, cleanroom"
46,Staubli TX60,Staubli,LOW,Common 6-axis model
47,KUKA KR C4,KUKA,LOW,Controller — catches listings titled by contro...
48,Kawasaki RS010L,Kawasaki,LOW,Medium payload
49,Kawasaki ZD130,Kawasaki,LOW,Palletizing robot
50,Motoman GP25,Yaskawa,LOW,Newer general purpose
51,Comau robot arm,Comau,LOW,"Italian, common in automotive"
52,ABB IRC5 controller,ABB,LOW,Controller — catches listings titled by contro...
53,FANUC CR-7iA,FANUC,LOW,Collaborative robot
54,UR16e robot,Universal Robots,LOW,Heavy-duty cobot
55,Nachi robot arm,Nachi,LOW,"Japanese, welding and material handling"

In [7]:
search_terms.to_csv("search_terms.csv")

In [6]:
search_terms["Search This Exact Phrase"]
["FANUC robot", "UR10 robot", "Universal Robots UR"]

['FANUC robot', 'UR10 robot', 'Universal Robots UR']

## Robots_listing HTML Scrape

In [ ]:
      ### Add Serach Terms
    # search_terms = ["FANUC robot", "UR10 robot", "Universal Robots UR"]
    # for search_key in search_terms:
    #     page.get_by_placeholder("Search for anything").fill(search_key)
    #     page.get_by_placeholder("Search for anything").press("Enter")
    #     page.wait_for_timeout(2000)

<div class="srp-river-results clearfix" id="srp-river-results">

In [15]:
with open("robots_listing.html", "r", encoding="utf-8") as f:
    robots_listing_html = f.read()

In [16]:
soup  = BeautifulSoup(robots_listing_html, 'html.parser')

In [17]:
soup.find("div", id="srp-river-results").ul

<ul class="carousel__list" id="s0-2-54-0-9-8-4-4-0-3-0-1[0]-0-2-0-1-0-0-1-1-2-list"><li class="carousel__snap-point srp-carousel-list__item srp-multi-aspect__item--applied" style="margin-right:16px"><div><a _sp="p2351460.m43632.l8566" class="srp-carousel-list__item-link" href="https://www.ebay.com/sch/i.html?_nkw=FANUC+robot&amp;_sacat=0&amp;_from=R40&amp;LH_Sold=1&amp;rt=nc"><div>Over $2,000.00<span class="clipped">Remove filter</span><svg aria-hidden="true" class="icon icon--16" data-marko-key="@svg s0-2-54-0-9-8-4-4-0-3-0-1[0]-0-2-0-1-0-0-1-1-2-4[@0]-3[0]-0-0-0-2-1-6-0" focusable="false"><use href="#icon-close-16"></use></svg></div></a></div></li><li class="carousel__snap-point srp-carousel-list__item srp-multi-aspect__item--applied" style="margin-right:16px"><div><a _sp="p2351460.m43632.l8566" class="srp-carousel-list__item-link" href="https://www.ebay.com/sch/i.html?_nkw=FANUC+robot&amp;_sacat=0&amp;_from=R40&amp;rt=nc&amp;_udlo=2000"><div>Sold listings<span class="clipped">Remove filter</span><svg aria-hidden="true" class="icon icon--16" data-marko-key="@svg s0-2-54-0-9-8-4-4-0-3-0-1[0]-0-2-0-1-0-0-1-1-2-4[@1]-3[1]-0-0-0-2-1-6-0" focusable="false"><use href="#icon-close-16"></use></svg></div></a></div></li><li class="carousel__snap-point srp-carousel-list__item srp-multi-aspect__item--applied"><div><a _sp="p2351460.m43632.l8568" class="srp-carousel-list__item-link clear-all" href="https://www.ebay.com/sch/i.html?_fsrp=1&amp;_nkw=FANUC+robot&amp;_oaa=1&amp;_vs=1"><div>Clear All<span class="clipped">Filters</span><svg aria-hidden="true" class="icon icon--16" data-marko-key="@svg s0-2-54-0-9-8-4-4-0-3-0-1[0]-0-2-0-1-0-0-1-1-2-4[@2]-3[2]-0-0-0-2-1-6-0" focusable="false"><use href="#icon-close-16"></use></svg></div></a></div></li></ul>

In [18]:
soup.find("div", id="srp-river-results").ul

<ul class="carousel__list" id="s0-2-54-0-9-8-4-4-0-3-0-1[0]-0-2-0-1-0-0-1-1-2-list"><li class="carousel__snap-point srp-carousel-list__item srp-multi-aspect__item--applied" style="margin-right:16px"><div><a _sp="p2351460.m43632.l8566" class="srp-carousel-list__item-link" href="https://www.ebay.com/sch/i.html?_nkw=FANUC+robot&amp;_sacat=0&amp;_from=R40&amp;LH_Sold=1&amp;rt=nc"><div>Over $2,000.00<span class="clipped">Remove filter</span><svg aria-hidden="true" class="icon icon--16" data-marko-key="@svg s0-2-54-0-9-8-4-4-0-3-0-1[0]-0-2-0-1-0-0-1-1-2-4[@0]-3[0]-0-0-0-2-1-6-0" focusable="false"><use href="#icon-close-16"></use></svg></div></a></div></li><li class="carousel__snap-point srp-carousel-list__item srp-multi-aspect__item--applied" style="margin-right:16px"><div><a _sp="p2351460.m43632.l8566" class="srp-carousel-list__item-link" href="https://www.ebay.com/sch/i.html?_nkw=FANUC+robot&amp;_sacat=0&amp;_from=R40&amp;rt=nc&amp;_udlo=2000"><div>Sold listings<span class="clipped">Remove filter</span><svg aria-hidden="true" class="icon icon--16" data-marko-key="@svg s0-2-54-0-9-8-4-4-0-3-0-1[0]-0-2-0-1-0-0-1-1-2-4[@1]-3[1]-0-0-0-2-1-6-0" focusable="false"><use href="#icon-close-16"></use></svg></div></a></div></li><li class="carousel__snap-point srp-carousel-list__item srp-multi-aspect__item--applied"><div><a _sp="p2351460.m43632.l8568" class="srp-carousel-list__item-link clear-all" href="https://www.ebay.com/sch/i.html?_fsrp=1&amp;_nkw=FANUC+robot&amp;_oaa=1&amp;_vs=1"><div>Clear All<span class="clipped">Filters</span><svg aria-hidden="true" class="icon icon--16" data-marko-key="@svg s0-2-54-0-9-8-4-4-0-3-0-1[0]-0-2-0-1-0-0-1-1-2-4[@2]-3[2]-0-0-0-2-1-6-0" focusable="false"><use href="#icon-close-16"></use></svg></div></a></div></li></ul>