# Extract Clean Readable Data From Json Data

In [2]:
import re
import json
import pandas as pd

In [3]:
json_data = pd.read_json("KUKA robot arm.json")

In [4]:
pd.DataFrame(list(json_data["Faunc Robot"]))

,product_title,sold_date,primary_container,secondary_container,product_image,product_link
0,ADE CON-1715 Series 350 ARM Robot Controller K...,"Sold Feb 13, 2026","$6,002.26||or Best Offer||+$2,485.61 delivery|...",usedeqsales ||99.7% positive (10.3K),https://www.ebay.com/itm/389612861143?_skw=KUK...,https://www.ebay.com/itm/389612861143?_skw=KUK...
1,KUKA 00-291-556 SmartPAD Flex Teach Pendant 00...,"Sold Feb 27, 2026","$2,499.99||Buy It Now||+$160.86 delivery||Loca...",njt-automation ||100% positive (4.1K),https://www.ebay.com/itm/306684345002?_skw=KUK...,https://www.ebay.com/itm/306684345002?_skw=KUK...
2,UFACTORY X-ARM 7 - Robotic Arm 7DoF - NEW | Op...,"Sold Jan 29, 2026","$5,500.00||1 bid||+$150.00 delivery||Located i...",fastrobo ||0% positive (0),https://www.ebay.com/itm/136963522445?_skw=KUK...,https://www.ebay.com/itm/136963522445?_skw=KUK...
3,PiPER 6DOF Mechanical Arm Opensource Multi-joi...,"Sold Feb 23, 2026","$3,135.00||$3,300.00||or Best Offer||+$15.00 d...",onebuymore ||99.6% positive (826),https://www.ebay.com/itm/197872611503?_skw=KUK...,https://www.ebay.com/itm/197872611503?_skw=KUK...
4,UFACTORY 6-Axis Robot Arm Lite 6 with Gripper ...,"Sold Mar 9, 2026","$3,250.00||or Best Offer||+$250.00 delivery||L...",dreamamericausa ||0% positive (311),https://www.ebay.com/itm/167926744193?_skw=KUK...,https://www.ebay.com/itm/167926744193?_skw=KUK...
5,Universal Robots UR3 CB3 Collaborative Robot A...,"Sold Mar 24, 2026","$2,036.00||31 bids||+$150.99 delivery||Located...",urubei_japan ||98.3% positive (7.6K),https://www.ebay.com/itm/117093737738?_skw=KUK...,https://www.ebay.com/itm/117093737738?_skw=KUK...
6,FAIRINO FR5 Collaborative Robot Arm 5kg Payloa...,"Sold Feb 2, 2026","$5,900.00||or Best Offer||Shipping not specifi...",he909998 ||100% positive (2),https://www.ebay.com/itm/306694121056?_skw=KUK...,https://www.ebay.com/itm/306694121056?_skw=KUK...
7,Universal Robots UR3 CB3 Collaborative Robot A...,"Sold Mar 17, 2026","$2,827.00||39 bids||+$150.99 delivery||Located...",urubei_japan ||98.3% positive (7.6K),https://www.ebay.com/itm/117079436945?_skw=KUK...,https://www.ebay.com/itm/117079436945?_skw=KUK...
8,KUKA KR C4 UL Compact Robot Controller 1106230...,"Sold Sep 17, 2025","$2,400.00||or Best Offer||+$187.00 delivery||L...",ysmetronics2010 ||99.5% positive (2.9K),https://www.ebay.com/itm/235920998155?_skw=KUK...,https://www.ebay.com/itm/235920998155?_skw=KUK...
9,LOT of 2 Adept 4 Axis Robot Arm w/ Cables & Co...,"Sold Feb 11, 2026","$4,799.99||$5,999.99||or Best Offer||Shipping ...",crochrc ||99.7% positive (4.6K),https://www.ebay.com/itm/114574437428?_skw=KUK...,https://www.ebay.com/itm/114574437428?_skw=KUK...
10,COMAU SMART-5 RACER 7-1.4 SAFE ROBOT With 6 ...,"Sold Sep 5, 2025","$2,712.20||or Best Offer||+$269.19 delivery||L...",industrial_part_solutions ||99.8% positive (3.2K),https://www.ebay.com/itm/375143866340?_skw=KUK...,https://www.ebay.com/itm/375143866340?_skw=KUK...
11,HIRATA ARM BASE ARM BASE AR-S270AE-4-200 ARS27...,"Sold Jan 22, 2026","$2,960.11||Buy It Now||+$71.22 delivery||Locat...",a-z_automatyka ||99.5% positive (8K),https://www.ebay.com/itm/326872817583?_skw=KUK...,https://www.ebay.com/itm/326872817583?_skw=KUK...
12,New Seiko Epson G10-851C Cleanroom SCARA Robot...,"Sold Jan 29, 2026","$8,999.99||1 bid||+$2,000.00 delivery||Located...",nevadasurplus-com ||100% positive (11.4K),https://www.ebay.com/itm/116995915910?_skw=KUK...,https://www.ebay.com/itm/116995915910?_skw=KUK...
13,TEL TOKYO ELECTRON DUAL ARM ROBOT CX80-001366-...,"Sold Oct 8, 2025","$2,200.00||or Best Offer||+$299.00 delivery||L...",gefen-tech1 ||100% positive (167),https://www.ebay.com/itm/365177445370?_skw=KUK...,https://www.ebay.com/itm/365177445370?_skw=KUK...
14,Kuka KR3 Robot with controller / Kuka KCP2 - F...,"Sold Jan 30, 2026","$3,750.00||Buy It Now||Free International Ship...",platinum-international ||98.8% positive (1.6K),https://www.ebay.com/itm/256204673020?_skw=KUK...,https://www.ebay.com/itm/256204673020?_skw=KUK...

In [5]:
pd.DataFrame(list(json_data["Faunc Robot"].values))

,product_title,sold_date,primary_container,secondary_container,product_image,product_link
0,ADE CON-1715 Series 350 ARM Robot Controller K...,"Sold Feb 13, 2026","$6,002.26||or Best Offer||+$2,485.61 delivery|...",usedeqsales ||99.7% positive (10.3K),https://www.ebay.com/itm/389612861143?_skw=KUK...,https://www.ebay.com/itm/389612861143?_skw=KUK...
1,KUKA 00-291-556 SmartPAD Flex Teach Pendant 00...,"Sold Feb 27, 2026","$2,499.99||Buy It Now||+$160.86 delivery||Loca...",njt-automation ||100% positive (4.1K),https://www.ebay.com/itm/306684345002?_skw=KUK...,https://www.ebay.com/itm/306684345002?_skw=KUK...
2,UFACTORY X-ARM 7 - Robotic Arm 7DoF - NEW | Op...,"Sold Jan 29, 2026","$5,500.00||1 bid||+$150.00 delivery||Located i...",fastrobo ||0% positive (0),https://www.ebay.com/itm/136963522445?_skw=KUK...,https://www.ebay.com/itm/136963522445?_skw=KUK...
3,PiPER 6DOF Mechanical Arm Opensource Multi-joi...,"Sold Feb 23, 2026","$3,135.00||$3,300.00||or Best Offer||+$15.00 d...",onebuymore ||99.6% positive (826),https://www.ebay.com/itm/197872611503?_skw=KUK...,https://www.ebay.com/itm/197872611503?_skw=KUK...
4,UFACTORY 6-Axis Robot Arm Lite 6 with Gripper ...,"Sold Mar 9, 2026","$3,250.00||or Best Offer||+$250.00 delivery||L...",dreamamericausa ||0% positive (311),https://www.ebay.com/itm/167926744193?_skw=KUK...,https://www.ebay.com/itm/167926744193?_skw=KUK...
5,Universal Robots UR3 CB3 Collaborative Robot A...,"Sold Mar 24, 2026","$2,036.00||31 bids||+$150.99 delivery||Located...",urubei_japan ||98.3% positive (7.6K),https://www.ebay.com/itm/117093737738?_skw=KUK...,https://www.ebay.com/itm/117093737738?_skw=KUK...
6,FAIRINO FR5 Collaborative Robot Arm 5kg Payloa...,"Sold Feb 2, 2026","$5,900.00||or Best Offer||Shipping not specifi...",he909998 ||100% positive (2),https://www.ebay.com/itm/306694121056?_skw=KUK...,https://www.ebay.com/itm/306694121056?_skw=KUK...
7,Universal Robots UR3 CB3 Collaborative Robot A...,"Sold Mar 17, 2026","$2,827.00||39 bids||+$150.99 delivery||Located...",urubei_japan ||98.3% positive (7.6K),https://www.ebay.com/itm/117079436945?_skw=KUK...,https://www.ebay.com/itm/117079436945?_skw=KUK...
8,KUKA KR C4 UL Compact Robot Controller 1106230...,"Sold Sep 17, 2025","$2,400.00||or Best Offer||+$187.00 delivery||L...",ysmetronics2010 ||99.5% positive (2.9K),https://www.ebay.com/itm/235920998155?_skw=KUK...,https://www.ebay.com/itm/235920998155?_skw=KUK...
9,LOT of 2 Adept 4 Axis Robot Arm w/ Cables & Co...,"Sold Feb 11, 2026","$4,799.99||$5,999.99||or Best Offer||Shipping ...",crochrc ||99.7% positive (4.6K),https://www.ebay.com/itm/114574437428?_skw=KUK...,https://www.ebay.com/itm/114574437428?_skw=KUK...
10,COMAU SMART-5 RACER 7-1.4 SAFE ROBOT With 6 ...,"Sold Sep 5, 2025","$2,712.20||or Best Offer||+$269.19 delivery||L...",industrial_part_solutions ||99.8% positive (3.2K),https://www.ebay.com/itm/375143866340?_skw=KUK...,https://www.ebay.com/itm/375143866340?_skw=KUK...
11,HIRATA ARM BASE ARM BASE AR-S270AE-4-200 ARS27...,"Sold Jan 22, 2026","$2,960.11||Buy It Now||+$71.22 delivery||Locat...",a-z_automatyka ||99.5% positive (8K),https://www.ebay.com/itm/326872817583?_skw=KUK...,https://www.ebay.com/itm/326872817583?_skw=KUK...
12,New Seiko Epson G10-851C Cleanroom SCARA Robot...,"Sold Jan 29, 2026","$8,999.99||1 bid||+$2,000.00 delivery||Located...",nevadasurplus-com ||100% positive (11.4K),https://www.ebay.com/itm/116995915910?_skw=KUK...,https://www.ebay.com/itm/116995915910?_skw=KUK...
13,TEL TOKYO ELECTRON DUAL ARM ROBOT CX80-001366-...,"Sold Oct 8, 2025","$2,200.00||or Best Offer||+$299.00 delivery||L...",gefen-tech1 ||100% positive (167),https://www.ebay.com/itm/365177445370?_skw=KUK...,https://www.ebay.com/itm/365177445370?_skw=KUK...
14,Kuka KR3 Robot with controller / Kuka KCP2 - F...,"Sold Jan 30, 2026","$3,750.00||Buy It Now||Free International Ship...",platinum-international ||98.8% positive (1.6K),https://www.ebay.com/itm/256204673020?_skw=KUK...,https://www.ebay.com/itm/256204673020?_skw=KUK...

In [6]:
search_terms = pd.read_csv(r"C:\Users\ASUS\OneDrive\Desktop\Web Scraping\03_eBay Data Collection-Upwork\search_terms.csv")
search_terms["Search This Exact Phrase"]

0              FANUC robot
1               UR10 robot
2                UR5 robot
3      Universal Robots UR
4            Motoman HP20D
5            Motoman robot
6            Yaskawa robot
7               KUKA KR 16
8              KUKA KR 210
9           KUKA robot arm
10            ABB IRB 4600
11            ABB IRB 2600
12            ABB IRB 6700
13             KUKA KR 150
14            FANUC M-10iA
15          FANUC R-2000iA
16           FANUC M-710iC
17          FANUC R-2000iC
18            FANUC M-20iD
19           ABB robot arm
20           FANUC LR Mate
21            FANUC M-20iA
22         Denso robot arm
23               UR3 robot
24      Kawasaki robot arm
25              UR5e robot
26    Mitsubishi robot arm
27           Yaskawa DX200
28          Motoman MA1440
29             UR10e robot
30         Kawasaki RS006L
31       Epson robot SCARA
32             KUKA KR 360
33               KUKA KR 6
34           FANUC M-900iA
35           FANUC M-900iB
36             ABB IRB 120
37            ABB IRB 6640
38            ABB IRB 1200
39          FANUC ARC Mate
40            FANUC R-30iB
41            Motoman MH50
42       Mitsubishi RV-7FL
43          Epson T6 robot
44           Denso VS-6577
45       Staubli robot arm
46            Staubli TX60
47              KUKA KR C4
48         Kawasaki RS010L
49          Kawasaki ZD130
50            Motoman GP25
51         Comau robot arm
52     ABB IRC5 controller
53            FANUC CR-7iA
54             UR16e robot
55         Nachi robot arm
Name: Search This Exact Phrase, dtype: object

In [7]:
all_dfs = []
for i in search_terms["Search This Exact Phrase"]:
    json_data = pd.read_json(f"{i}.json")
    if len(json_data) >= 1:
        df = pd.DataFrame(pd.DataFrame(list(json_data["Faunc Robot"])))
        df["search_term"] = i
        all_dfs.append(df)
        

final_df = pd.concat(all_dfs, ignore_index=True)

In [8]:
final_df

,product_title,sold_date,primary_container,secondary_container,product_image,product_link,search_term
0,GUARANTEED! FANUC LTD GMF ROBOTICS S-5 ARC MAT...,"Sold Mar 26, 2026","$4,999.95||or Best Offer||+$760.13 delivery||L...",tcb3162 ||100% positive (34.9K),https://www.ebay.com/itm/326087574965?_skw=FAN...,https://www.ebay.com/itm/326087574965?_skw=FAN...,FANUC robot
1,Fanuc A05B-2696-B001 CONTROL R-30iB Mini Plus ...,"Sold Aug 28, 2025","$2,400.00||or Best Offer||+$87.00 delivery||Lo...",ysmetronics2010 ||99.5% positive (2.9K),https://www.ebay.com/itm/235882269777?_skw=FAN...,https://www.ebay.com/itm/235882269777?_skw=FAN...,FANUC robot
2,FANUC R-30iB Plus 🤖 ROBOT LR MATE 200iD + A05B...,"Sold Mar 21, 2026","$15,000.00||or Best Offer||+$20.00 delivery||L...",plccompany_mx ||100% positive (427),https://www.ebay.com/itm/136952732178?_skw=FAN...,https://www.ebay.com/itm/136952732178?_skw=FAN...,FANUC robot
3,New FANUC A05B-2256-C101#EGN TEACH PENDANT iPe...,"Sold Oct 22, 2025","$2,106.14||or Best Offer||Free International S...",mattexr ||98.8% positive (367),https://www.ebay.com/itm/388505577933?_skw=FAN...,https://www.ebay.com/itm/388505577933?_skw=FAN...,FANUC robot
4,FANUC A290-7324-T503 / A2907324T503 (USED) | O...,"Sold Mar 16, 2026","$6,099.37||Buy It Now||+$72.77 delivery||Locat...",radwellcanada ||99% positive (603),https://www.ebay.com/itm/386961036420?_skw=FAN...,https://www.ebay.com/itm/386961036420?_skw=FAN...,FANUC robot
...,...,...,...,...,...,...,...
726,Universal Robots UR3 CB3 Collaborative Robot A...,"Sold Mar 17, 2026","$2,827.00||39 bids||+$150.99 delivery||Located...",urubei_japan ||98.3% positive (7.6K),https://www.ebay.com/itm/117079436945?_skw=Nac...,https://www.ebay.com/itm/117079436945?_skw=Nac...,Nachi robot arm
727,COMAU SMART-5 RACER 7-1.4 SAFE ROBOT With 6 ...,"Sold Sep 5, 2025","$2,712.20||or Best Offer||+$269.19 delivery||L...",industrial_part_solutions ||99.8% positive (3.2K),https://www.ebay.com/itm/375143866340?_skw=Nac...,https://www.ebay.com/itm/375143866340?_skw=Nac...,Nachi robot arm
728,HIRATA ARM BASE ARM BASE AR-S270AE-4-200 ARS27...,"Sold Jan 22, 2026","$2,960.11||Buy It Now||+$71.22 delivery||Locat...",a-z_automatyka ||99.5% positive (8K),https://www.ebay.com/itm/326872817583?_skw=Nac...,https://www.ebay.com/itm/326872817583?_skw=Nac...,Nachi robot arm
729,New Seiko Epson G10-851C Cleanroom SCARA Robot...,"Sold Jan 29, 2026","$8,999.99||1 bid||+$2,000.00 delivery||Located...",nevadasurplus-com ||100% positive (11.4K),https://www.ebay.com/itm/116995915910?_skw=Nac...,https://www.ebay.com/itm/116995915910?_skw=Nac...,Nachi robot arm
730,MILARA INCORPORATED SINGLE ARM ROBOT ATM-105-1...,"Sold Mar 6, 2026","$3,538.52||or Best Offer||+$330.37 delivery||L...",habibu2005 ||100% positive (5K),https://www.ebay.com/itm/257393241318?_skw=Nac...,https://www.ebay.com/itm/257393241318?_skw=Nac...,Nachi robot arm

In [10]:
# final_df.to_excel("scraped_robots_data.xlsx", sheet_name="scraped_data", index=False)

# Cleaning scraped_robots_Data

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)   # show all columns
# pd.set_option('display.max_rows', None)      # show all rows (be careful!)
pd.set_option('display.max_colwidth', None)  # show full text (very important for you)

In [2]:
df = pd.read_excel("scraped_robots_data.xlsx",sheet_name="scraped_data" )
df.head()

,product_title,sold_date,primary_container,secondary_container,product_image,product_link,search_term
0,GUARANTEED! FANUC LTD GMF ROBOTICS S-5 ARC MATE ROBOT SYSTEM A05B-1203-B251 | Opens in a new window or tab,"Sold Mar 26, 2026","$4,999.95||or Best Offer||+$760.13 delivery||Located in United States||View similar active items||Sell one like this",tcb3162 ||100% positive (34.9K),https://www.ebay.com/itm/326087574965?_skw=FANUC+robot&epid=4066690834&itmmeta=01KPCJXEMG5SHQVGDPYSDA5NA6&hash=item4bec5585b5:g:aOsAAOSw0qZmGZib&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xAWq8QhMLQsU8gg08bcq403RsqDXoYe7H%2FDwG051SnQX6BjZx0WxYDwUOz1X%2FwDOALNJTSzvWf3oZ8j4XO84knIAmjL9XZLiRDzcEsQtgP5zl00ZqvydbAlG00j6EXzC4PVWVE3bU5w%2BvDMMTPNiprYJ0uN5Ql6XZoy5MxfnTzsWAafkw1b053zpL6pyUw8lbycye1HVeTZVypwLDjWcDNYKL%2B3SePIt6tMNCmYKFicntFFsGNRaHcHut%2BeHfjzvnA%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/326087574965?_skw=FANUC+robot&epid=4066690834&itmmeta=01KPCJXEMG5SHQVGDPYSDA5NA6&hash=item4bec5585b5:g:aOsAAOSw0qZmGZib&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xAWq8QhMLQsU8gg08bcq403RsqDXoYe7H%2FDwG051SnQX6BjZx0WxYDwUOz1X%2FwDOALNJTSzvWf3oZ8j4XO84knIAmjL9XZLiRDzcEsQtgP5zl00ZqvydbAlG00j6EXzC4PVWVE3bU5w%2BvDMMTPNiprYJ0uN5Ql6XZoy5MxfnTzsWAafkw1b053zpL6pyUw8lbycye1HVeTZVypwLDjWcDNYKL%2B3SePIt6tMNCmYKFicntFFsGNRaHcHut%2BeHfjzvnA%3D%7Ctkp%3ABk9SR67q9ZKzZw,FANUC robot
1,Fanuc A05B-2696-B001 CONTROL R-30iB Mini Plus for CRX-10iA/L Collaborative Robot | Opens in a new window or tab,"Sold Aug 28, 2025","$2,400.00||or Best Offer||+$87.00 delivery||Located in Israel||View similar active items||Sell one like this",ysmetronics2010 ||99.5% positive (2.9K),https://www.ebay.com/itm/235882269777?_skw=FANUC+robot&itmmeta=01KPCJXEMGDR015Y9QQHHMX3QD&hash=item36ebadcc51:g:NDMAAOSwtlNnaXLm&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xBeTmmJKwqqUeyaIG08npIsPw%2BQ5cOet43SgDvdLVZo7UlsM3lX4tLGcw5cqwJPK0163QcT5Gdww4ggasAI7rA5%2B1vOLp5MnPZWMC%2Bj9A798weoDj%2FMW2FQnTPmpdaLliwIgfOIrFVizYXfdrHQ4LxLJfHSKOg4yA34xL0vH7VnBXa0VJZV6Y28kOiI8PT%2FBmus%2FWVDWpeR6CMErgoDQ5c28oCY%2BvdrsI5hNa6BmiFpwEXhZcq%2BXRy3KpoqlB9bWy4%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/235882269777?_skw=FANUC+robot&itmmeta=01KPCJXEMGDR015Y9QQHHMX3QD&hash=item36ebadcc51:g:NDMAAOSwtlNnaXLm&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xBeTmmJKwqqUeyaIG08npIsPw%2BQ5cOet43SgDvdLVZo7UlsM3lX4tLGcw5cqwJPK0163QcT5Gdww4ggasAI7rA5%2B1vOLp5MnPZWMC%2Bj9A798weoDj%2FMW2FQnTPmpdaLliwIgfOIrFVizYXfdrHQ4LxLJfHSKOg4yA34xL0vH7VnBXa0VJZV6Y28kOiI8PT%2FBmus%2FWVDWpeR6CMErgoDQ5c28oCY%2BvdrsI5hNa6BmiFpwEXhZcq%2BXRy3KpoqlB9bWy4%3D%7Ctkp%3ABk9SR67q9ZKzZw,FANUC robot
2,FANUC R-30iB Plus 🤖 ROBOT LR MATE 200iD + A05B-2256-C103#EMH fully working | Opens in a new window or tab,"Sold Mar 21, 2026","$15,000.00||or Best Offer||+$20.00 delivery||Located in Mexico||Free returns||View similar active items||Sell one like this",plccompany_mx ||100% positive (427),https://www.ebay.com/itm/136952732178?_skw=FANUC+robot&itmmeta=01KPCJXEMGWT5ZQ5B3SX3560RS&hash=item1fe304da12:g:qSYAAeSwpMhpaXWH&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xBsnbgeG0KdEsFRSar6BqDoD3ATpF10fFFgXRZaNlDdpwIRpeY9u9%2BHe75PvCfaDguXu%2BlbDRHkuB%2BjiEKWyzLNyxDdFimycBj6rpCSbwRrsmkAl6znHfxQFEg8g4WfZce8ysitTL%2BqTwuJA6vBWUX21XsrChJRV8VJ26akms4oTf6CnGqOLjjhxGx%2FxvyT7M2gdHntyRft4O3RYx9xZOhs04P6SijNxw6qpHVYFdaCrDiW7WhUuCHjD0HkPTPWXwivYFHKjP0e3lrTGnh%2BlzQfvzrRMnayvInETb2DcIukSQ%3D%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/136952732178?_skw=FANUC+robot&itmmeta=01KPCJXEMGWT5ZQ5B3SX3560RS&hash=item1fe304da12:g:qSYAAeSwpMhpaXWH&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xBsnbgeG0KdEsFRSar6BqDoD3ATpF10fFFgXRZaNlDdpwIRpeY9u9%2BHe75PvCfaDguXu%2BlbDRHkuB%2BjiEKWyzLNyxDdFimycBj6rpCSbwRrsmkAl6znHfxQFEg8g4WfZce8ysitTL%2BqTwuJA6vBWUX21XsrChJRV8VJ26akms4oTf6CnGqOLjjhxGx%2FxvyT7M2gdHntyRft4O3RYx9xZOhs04P6SijNxw6qpHVYFdaCrDiW7WhUuCHjD0HkPTPWXwivYFHKjP0e3lrTGnh%2BlzQfvzrRMnayvInETb2DcIukSQ%3D%3D%7Ctkp%3ABk9SR67q9ZKzZw,FANUC robot
3,New FANUC A05B-2256-C101#EGN TEACH PENDANT iPendant | Opens in a new window or tab,"Sold Oct 22, 2025","$2,106.14||or Best Offer||Free International Shipping||Located in United States||Free returns||View similar active items||Sell one like this",mattexr ||98.8% positive (367),https://www.ebay.com/itm/388505577933?_skw=FANUC+robot&itmmeta=01KPCJXEMGPE5SNSQRTJCGJBMN&hash=item5a74bca9cd:g:fGcAAOSwAW1oPX8M&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xAbys3a9Ca%2FepseS55HRhlpko2yEzPBkBwtRVd31OLSCLEGAUJB62CH4E2Y3QNRzxALkjNkDFgFHN8jFcu4oIqSQSKn%2BTBlyaeTNERUvtnILEiSA4QMG4XeGWJBvthX5DgV6492RjsbJHJvAThz%2BA6IWH64Q06Cu2WHUir%2B8P7Dxo8PqBcDg3zUmy7RUgwN4gRIaKckhCSAE9x6kfjYwoKc92SQ3Ur8Cto7PC2on%2BPQRWAkP9kNtiqm2nODFu2swrAlraUgpyo1SfSv5RpZS3B%2FFMS%2F0MpjfNcdZdOpSO7TVA%3D%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/388505577933?_skw=FANUC+robot&itmmeta=01KPCJXEMGPE5SNSQRTJCGJBMN&hash=item5a74bca9cd:g:fGcAAOSwAW1oPX8M&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xAbys3a9Ca%2FepseS55HRhlpko2yEzPBkBwtRVd31OLSCLEGAUJB62CH4E2Y3QNRzxALkjNkDFgFHN8jFcu4oIqSQSKn%2BTBlyaeTNERUvtnILEiSA4QMG4XeGWJBvthX5DgV6492RjsbJHJvAThz%2BA6IWH64Q06Cu2WHUir%2B8P7Dxo8PqBcDg3zUmy7RUgwN4gRIaKckhCSAE9x6kfjYwoKc92SQ3Ur8Cto7PC2on%2BPQRWAkP9kNtiqm2nODFu2swrAlraUgpyo1SfSv5RpZS3B%2FFMS%2F0MpjfNcdZdOpSO7TVA%3D%3D%7Ctkp%3ABk9SR67q9ZKzZw,FANUC robot
4,FANUC A290-7324-T503 / A2907324T503 (USED) | Opens in a new window or tab,"Sold Mar 16, 2026","$6,099.37||Buy It Now||+$72.77 delivery||Located in Canada||View similar active items||Sell one like this",radwellcanada ||99% positive (603),https://www.ebay.com/itm/386961036420?_skw=FANUC+robot&itmmeta=01KPCJXEMG237SVP79W59QCQ5Y&hash=item5a18acd484:g:cX0AAeSwYFxpzoXd&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xCv%2BcTC9isDQcR8wglHyJdYmkciwOrGcrJxdqD3CT7QMQNfEGvHjhxYRGNNaOyUFjAcwMGIyU4f%2FkE3hvF%2B5jSpriSBg%2FNLgCmMTjk7eIw0VpWgDtZ8n9ikDz1WZiyioWH0NiD6b6ZaBnUR1%2Bs4MhfQurwkA%2BHZa1GFhcIPnVit7V8TyT7a5gyQQK2tBrNUJzFQA0GCI7CrFzL1Eb9B2%2F0S4cbKM98wezer%2FcnH7T1Ioz%2BwxKHsgs%2BPuOb2ES1gW40%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/386961036420?_skw=FANUC+robot&itmmeta=01KPCJXEMG237SVP79W59QCQ5Y&hash=item5a18acd484:g:cX0AAeSwYFxpzoXd&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xCv%2BcTC9isDQcR8wglHyJdYmkciwOrGcrJxdqD3CT7QMQNfEGvHjhxYRGNNaOyUFjAcwMGIyU4f%2FkE3hvF%2B5jSpriSBg%2FNLgCmMTjk7eIw0VpWgDtZ8n9ikDz1WZiyioWH0NiD6b6ZaBnUR1%2Bs4MhfQurwkA%2BHZa1GFhcIPnVit7V8TyT7a5gyQQK2tBrNUJzFQA0GCI7CrFzL1Eb9B2%2F0S4cbKM98wezer%2FcnH7T1Ioz%2BwxKHsgs%2BPuOb2ES1gW40%3D%7Ctkp%3ABk9SR67q9ZKzZw,FANUC robot

In [3]:
df["listing_title"] = df["product_title"].str.split("|").apply(lambda x : x[:-1] if "Opens in a new window or tab" in x[-1] else x[:]).apply(lambda x : "".join(x))

In [4]:
df.head()

,product_title,sold_date,primary_container,secondary_container,product_image,product_link,search_term,listing_title
0,GUARANTEED! FANUC LTD GMF ROBOTICS S-5 ARC MATE ROBOT SYSTEM A05B-1203-B251 | Opens in a new window or tab,"Sold Mar 26, 2026","$4,999.95||or Best Offer||+$760.13 delivery||Located in United States||View similar active items||Sell one like this",tcb3162 ||100% positive (34.9K),https://www.ebay.com/itm/326087574965?_skw=FANUC+robot&epid=4066690834&itmmeta=01KPCJXEMG5SHQVGDPYSDA5NA6&hash=item4bec5585b5:g:aOsAAOSw0qZmGZib&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xAWq8QhMLQsU8gg08bcq403RsqDXoYe7H%2FDwG051SnQX6BjZx0WxYDwUOz1X%2FwDOALNJTSzvWf3oZ8j4XO84knIAmjL9XZLiRDzcEsQtgP5zl00ZqvydbAlG00j6EXzC4PVWVE3bU5w%2BvDMMTPNiprYJ0uN5Ql6XZoy5MxfnTzsWAafkw1b053zpL6pyUw8lbycye1HVeTZVypwLDjWcDNYKL%2B3SePIt6tMNCmYKFicntFFsGNRaHcHut%2BeHfjzvnA%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/326087574965?_skw=FANUC+robot&epid=4066690834&itmmeta=01KPCJXEMG5SHQVGDPYSDA5NA6&hash=item4bec5585b5:g:aOsAAOSw0qZmGZib&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xAWq8QhMLQsU8gg08bcq403RsqDXoYe7H%2FDwG051SnQX6BjZx0WxYDwUOz1X%2FwDOALNJTSzvWf3oZ8j4XO84knIAmjL9XZLiRDzcEsQtgP5zl00ZqvydbAlG00j6EXzC4PVWVE3bU5w%2BvDMMTPNiprYJ0uN5Ql6XZoy5MxfnTzsWAafkw1b053zpL6pyUw8lbycye1HVeTZVypwLDjWcDNYKL%2B3SePIt6tMNCmYKFicntFFsGNRaHcHut%2BeHfjzvnA%3D%7Ctkp%3ABk9SR67q9ZKzZw,FANUC robot,GUARANTEED! FANUC LTD GMF ROBOTICS S-5 ARC MATE ROBOT SYSTEM A05B-1203-B251
1,Fanuc A05B-2696-B001 CONTROL R-30iB Mini Plus for CRX-10iA/L Collaborative Robot | Opens in a new window or tab,"Sold Aug 28, 2025","$2,400.00||or Best Offer||+$87.00 delivery||Located in Israel||View similar active items||Sell one like this",ysmetronics2010 ||99.5% positive (2.9K),https://www.ebay.com/itm/235882269777?_skw=FANUC+robot&itmmeta=01KPCJXEMGDR015Y9QQHHMX3QD&hash=item36ebadcc51:g:NDMAAOSwtlNnaXLm&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xBeTmmJKwqqUeyaIG08npIsPw%2BQ5cOet43SgDvdLVZo7UlsM3lX4tLGcw5cqwJPK0163QcT5Gdww4ggasAI7rA5%2B1vOLp5MnPZWMC%2Bj9A798weoDj%2FMW2FQnTPmpdaLliwIgfOIrFVizYXfdrHQ4LxLJfHSKOg4yA34xL0vH7VnBXa0VJZV6Y28kOiI8PT%2FBmus%2FWVDWpeR6CMErgoDQ5c28oCY%2BvdrsI5hNa6BmiFpwEXhZcq%2BXRy3KpoqlB9bWy4%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/235882269777?_skw=FANUC+robot&itmmeta=01KPCJXEMGDR015Y9QQHHMX3QD&hash=item36ebadcc51:g:NDMAAOSwtlNnaXLm&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xBeTmmJKwqqUeyaIG08npIsPw%2BQ5cOet43SgDvdLVZo7UlsM3lX4tLGcw5cqwJPK0163QcT5Gdww4ggasAI7rA5%2B1vOLp5MnPZWMC%2Bj9A798weoDj%2FMW2FQnTPmpdaLliwIgfOIrFVizYXfdrHQ4LxLJfHSKOg4yA34xL0vH7VnBXa0VJZV6Y28kOiI8PT%2FBmus%2FWVDWpeR6CMErgoDQ5c28oCY%2BvdrsI5hNa6BmiFpwEXhZcq%2BXRy3KpoqlB9bWy4%3D%7Ctkp%3ABk9SR67q9ZKzZw,FANUC robot,Fanuc A05B-2696-B001 CONTROL R-30iB Mini Plus for CRX-10iA/L Collaborative Robot
2,FANUC R-30iB Plus 🤖 ROBOT LR MATE 200iD + A05B-2256-C103#EMH fully working | Opens in a new window or tab,"Sold Mar 21, 2026","$15,000.00||or Best Offer||+$20.00 delivery||Located in Mexico||Free returns||View similar active items||Sell one like this",plccompany_mx ||100% positive (427),https://www.ebay.com/itm/136952732178?_skw=FANUC+robot&itmmeta=01KPCJXEMGWT5ZQ5B3SX3560RS&hash=item1fe304da12:g:qSYAAeSwpMhpaXWH&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xBsnbgeG0KdEsFRSar6BqDoD3ATpF10fFFgXRZaNlDdpwIRpeY9u9%2BHe75PvCfaDguXu%2BlbDRHkuB%2BjiEKWyzLNyxDdFimycBj6rpCSbwRrsmkAl6znHfxQFEg8g4WfZce8ysitTL%2BqTwuJA6vBWUX21XsrChJRV8VJ26akms4oTf6CnGqOLjjhxGx%2FxvyT7M2gdHntyRft4O3RYx9xZOhs04P6SijNxw6qpHVYFdaCrDiW7WhUuCHjD0HkPTPWXwivYFHKjP0e3lrTGnh%2BlzQfvzrRMnayvInETb2DcIukSQ%3D%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/136952732178?_skw=FANUC+robot&itmmeta=01KPCJXEMGWT5ZQ5B3SX3560RS&hash=item1fe304da12:g:qSYAAeSwpMhpaXWH&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xBsnbgeG0KdEsFRSar6BqDoD3ATpF10fFFgXRZaNlDdpwIRpeY9u9%2BHe75PvCfaDguXu%2BlbDRHkuB%2BjiEKWyzLNyxDdFimycBj6rpCSbwRrsmkAl6znHfxQFEg8g4WfZce8ysitTL%2BqTwuJA6vBWUX21XsrChJRV8VJ26akms4oTf6CnGqOLjjhxGx%2FxvyT7M2gdHntyRft4O3RYx9xZOhs04P6SijNxw6qpHVYFdaCrDiW7WhUuCHjD0HkPTPWXwivYFHKjP0e3lrTGnh%2BlzQfvzrRMnayvInETb2DcIukSQ%3D%3D%7Ctkp%3ABk9SR67q9ZKzZw,FANUC robot,FANUC R-30iB Plus 🤖 ROBOT LR MATE 200iD + A05B-2256-C103#EMH fully working
3,New FANUC A05B-2256-C101#EGN TEACH PENDANT iPendant | Opens in a new window or tab,"Sold Oct 22, 2025","$2,106.14||or Best Offer||Free International Shipping||Located in United States||Free returns||View similar active items||Sell one like this",mattexr ||98.8% positive (367),https://www.ebay.com/itm/388505577933?_skw=FANUC+robot&itmmeta=01KPCJXEMGPE5SNSQRTJCGJBMN&hash=item5a74bca9cd:g:fGcAAOSwAW1oPX8M&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xAbys3a9Ca%2FepseS55HRhlpko2yEzPBkBwtRVd31OLSCLEGAUJB62CH4E2Y3QNRzxALkjNkDFgFHN8jFcu4oIqSQSKn%2BTBlyaeTNERUvtnILEiSA4QMG4XeGWJBvthX5DgV6492RjsbJHJvAThz%2BA6IWH64Q06Cu2WHUir%2B8P7Dxo8PqBcDg3zUmy7RUgwN4gRIaKckhCSAE9x6kfjYwoKc92SQ3Ur8Cto7PC2on%2BPQRWAkP9kNtiqm2nODFu2swrAlraUgpyo1SfSv5RpZS3B%2FFMS%2F0MpjfNcdZdOpSO7TVA%3D%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/388505577933?_skw=FANUC+robot&itmmeta=01KPCJXEMGPE5SNSQRTJCGJBMN&hash=item5a74bca9cd:g:fGcAAOSwAW1oPX8M&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xAbys3a9Ca%2FepseS55HRhlpko2yEzPBkBwtRVd31OLSCLEGAUJB62CH4E2Y3QNRzxALkjNkDFgFHN8jFcu4oIqSQSKn%2BTBlyaeTNERUvtnILEiSA4QMG4XeGWJBvthX5DgV6492RjsbJHJvAThz%2BA6IWH64Q06Cu2WHUir%2B8P7Dxo8PqBcDg3zUmy7RUgwN4gRIaKckhCSAE9x6kfjYwoKc92SQ3Ur8Cto7PC2on%2BPQRWAkP9kNtiqm2nODFu2swrAlraUgpyo1SfSv5RpZS3B%2FFMS%2F0MpjfNcdZdOpSO7TVA%3D%3D%7Ctkp%3ABk9SR67q9ZKzZw,FANUC robot,New FANUC A05B-2256-C101#EGN TEACH PENDANT iPendant
4,FANUC A290-7324-T503 / A2907324T503 (USED) | Opens in a new window or tab,"Sold Mar 16, 2026","$6,099.37||Buy It Now||+$72.77 delivery||Located in Canada||View similar active items||Sell one like this",radwellcanada ||99% positive (603),https://www.ebay.com/itm/386961036420?_skw=FANUC+robot&itmmeta=01KPCJXEMG237SVP79W59QCQ5Y&hash=item5a18acd484:g:cX0AAeSwYFxpzoXd&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xCv%2BcTC9isDQcR8wglHyJdYmkciwOrGcrJxdqD3CT7QMQNfEGvHjhxYRGNNaOyUFjAcwMGIyU4f%2FkE3hvF%2B5jSpriSBg%2FNLgCmMTjk7eIw0VpWgDtZ8n9ikDz1WZiyioWH0NiD6b6ZaBnUR1%2Bs4MhfQurwkA%2BHZa1GFhcIPnVit7V8TyT7a5gyQQK2tBrNUJzFQA0GCI7CrFzL1Eb9B2%2F0S4cbKM98wezer%2FcnH7T1Ioz%2BwxKHsgs%2BPuOb2ES1gW40%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/386961036420?_skw=FANUC+robot&itmmeta=01KPCJXEMG237SVP79W59QCQ5Y&hash=item5a18acd484:g:cX0AAeSwYFxpzoXd&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xCv%2BcTC9isDQcR8wglHyJdYmkciwOrGcrJxdqD3CT7QMQNfEGvHjhxYRGNNaOyUFjAcwMGIyU4f%2FkE3hvF%2B5jSpriSBg%2FNLgCmMTjk7eIw0VpWgDtZ8n9ikDz1WZiyioWH0NiD6b6ZaBnUR1%2Bs4MhfQurwkA%2BHZa1GFhcIPnVit7V8TyT7a5gyQQK2tBrNUJzFQA0GCI7CrFzL1Eb9B2%2F0S4cbKM98wezer%2FcnH7T1Ioz%2BwxKHsgs%2BPuOb2ES1gW40%3D%7Ctkp%3ABk9SR67q9ZKzZw,FANUC robot,FANUC A290-7324-T503 / A2907324T503 (USED)

In [5]:
df["sold_date"].str.removeprefix(prefix="Sold")

0        Mar 26, 2026
1        Aug 28, 2025
2        Mar 21, 2026
3        Oct 22, 2025
4        Mar 16, 2026
            ...
726      Mar 17, 2026
727       Sep 5, 2025
728      Jan 22, 2026
729      Jan 29, 2026
730       Mar 6, 2026
Name: sold_date, Length: 731, dtype: object

In [6]:
df["sale_date"] = pd.to_datetime(df["sold_date"].str.removeprefix(prefix="Sold"))

In [9]:
df.columns

Index(['product_title', 'sold_date', 'primary_container',
       'secondary_container', 'product_image', 'product_link', 'search_term',
       'listing_title', 'sale_date'],
      dtype='object')

In [12]:
# Rearranging columns and droping unnecessary column
df = df[["search_term", "listing_title", "sale_date", "primary_container",	"secondary_container", "product_link", "product_image"]]
df.head()

,search_term,listing_title,sale_date,primary_container,secondary_container,product_link,product_image
0,FANUC robot,GUARANTEED! FANUC LTD GMF ROBOTICS S-5 ARC MATE ROBOT SYSTEM A05B-1203-B251,2026-03-26,"$4,999.95||or Best Offer||+$760.13 delivery||Located in United States||View similar active items||Sell one like this",tcb3162 ||100% positive (34.9K),https://www.ebay.com/itm/326087574965?_skw=FANUC+robot&epid=4066690834&itmmeta=01KPCJXEMG5SHQVGDPYSDA5NA6&hash=item4bec5585b5:g:aOsAAOSw0qZmGZib&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xAWq8QhMLQsU8gg08bcq403RsqDXoYe7H%2FDwG051SnQX6BjZx0WxYDwUOz1X%2FwDOALNJTSzvWf3oZ8j4XO84knIAmjL9XZLiRDzcEsQtgP5zl00ZqvydbAlG00j6EXzC4PVWVE3bU5w%2BvDMMTPNiprYJ0uN5Ql6XZoy5MxfnTzsWAafkw1b053zpL6pyUw8lbycye1HVeTZVypwLDjWcDNYKL%2B3SePIt6tMNCmYKFicntFFsGNRaHcHut%2BeHfjzvnA%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/326087574965?_skw=FANUC+robot&epid=4066690834&itmmeta=01KPCJXEMG5SHQVGDPYSDA5NA6&hash=item4bec5585b5:g:aOsAAOSw0qZmGZib&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xAWq8QhMLQsU8gg08bcq403RsqDXoYe7H%2FDwG051SnQX6BjZx0WxYDwUOz1X%2FwDOALNJTSzvWf3oZ8j4XO84knIAmjL9XZLiRDzcEsQtgP5zl00ZqvydbAlG00j6EXzC4PVWVE3bU5w%2BvDMMTPNiprYJ0uN5Ql6XZoy5MxfnTzsWAafkw1b053zpL6pyUw8lbycye1HVeTZVypwLDjWcDNYKL%2B3SePIt6tMNCmYKFicntFFsGNRaHcHut%2BeHfjzvnA%3D%7Ctkp%3ABk9SR67q9ZKzZw
1,FANUC robot,Fanuc A05B-2696-B001 CONTROL R-30iB Mini Plus for CRX-10iA/L Collaborative Robot,2025-08-28,"$2,400.00||or Best Offer||+$87.00 delivery||Located in Israel||View similar active items||Sell one like this",ysmetronics2010 ||99.5% positive (2.9K),https://www.ebay.com/itm/235882269777?_skw=FANUC+robot&itmmeta=01KPCJXEMGDR015Y9QQHHMX3QD&hash=item36ebadcc51:g:NDMAAOSwtlNnaXLm&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xBeTmmJKwqqUeyaIG08npIsPw%2BQ5cOet43SgDvdLVZo7UlsM3lX4tLGcw5cqwJPK0163QcT5Gdww4ggasAI7rA5%2B1vOLp5MnPZWMC%2Bj9A798weoDj%2FMW2FQnTPmpdaLliwIgfOIrFVizYXfdrHQ4LxLJfHSKOg4yA34xL0vH7VnBXa0VJZV6Y28kOiI8PT%2FBmus%2FWVDWpeR6CMErgoDQ5c28oCY%2BvdrsI5hNa6BmiFpwEXhZcq%2BXRy3KpoqlB9bWy4%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/235882269777?_skw=FANUC+robot&itmmeta=01KPCJXEMGDR015Y9QQHHMX3QD&hash=item36ebadcc51:g:NDMAAOSwtlNnaXLm&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xBeTmmJKwqqUeyaIG08npIsPw%2BQ5cOet43SgDvdLVZo7UlsM3lX4tLGcw5cqwJPK0163QcT5Gdww4ggasAI7rA5%2B1vOLp5MnPZWMC%2Bj9A798weoDj%2FMW2FQnTPmpdaLliwIgfOIrFVizYXfdrHQ4LxLJfHSKOg4yA34xL0vH7VnBXa0VJZV6Y28kOiI8PT%2FBmus%2FWVDWpeR6CMErgoDQ5c28oCY%2BvdrsI5hNa6BmiFpwEXhZcq%2BXRy3KpoqlB9bWy4%3D%7Ctkp%3ABk9SR67q9ZKzZw
2,FANUC robot,FANUC R-30iB Plus 🤖 ROBOT LR MATE 200iD + A05B-2256-C103#EMH fully working,2026-03-21,"$15,000.00||or Best Offer||+$20.00 delivery||Located in Mexico||Free returns||View similar active items||Sell one like this",plccompany_mx ||100% positive (427),https://www.ebay.com/itm/136952732178?_skw=FANUC+robot&itmmeta=01KPCJXEMGWT5ZQ5B3SX3560RS&hash=item1fe304da12:g:qSYAAeSwpMhpaXWH&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xBsnbgeG0KdEsFRSar6BqDoD3ATpF10fFFgXRZaNlDdpwIRpeY9u9%2BHe75PvCfaDguXu%2BlbDRHkuB%2BjiEKWyzLNyxDdFimycBj6rpCSbwRrsmkAl6znHfxQFEg8g4WfZce8ysitTL%2BqTwuJA6vBWUX21XsrChJRV8VJ26akms4oTf6CnGqOLjjhxGx%2FxvyT7M2gdHntyRft4O3RYx9xZOhs04P6SijNxw6qpHVYFdaCrDiW7WhUuCHjD0HkPTPWXwivYFHKjP0e3lrTGnh%2BlzQfvzrRMnayvInETb2DcIukSQ%3D%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/136952732178?_skw=FANUC+robot&itmmeta=01KPCJXEMGWT5ZQ5B3SX3560RS&hash=item1fe304da12:g:qSYAAeSwpMhpaXWH&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xBsnbgeG0KdEsFRSar6BqDoD3ATpF10fFFgXRZaNlDdpwIRpeY9u9%2BHe75PvCfaDguXu%2BlbDRHkuB%2BjiEKWyzLNyxDdFimycBj6rpCSbwRrsmkAl6znHfxQFEg8g4WfZce8ysitTL%2BqTwuJA6vBWUX21XsrChJRV8VJ26akms4oTf6CnGqOLjjhxGx%2FxvyT7M2gdHntyRft4O3RYx9xZOhs04P6SijNxw6qpHVYFdaCrDiW7WhUuCHjD0HkPTPWXwivYFHKjP0e3lrTGnh%2BlzQfvzrRMnayvInETb2DcIukSQ%3D%3D%7Ctkp%3ABk9SR67q9ZKzZw
3,FANUC robot,New FANUC A05B-2256-C101#EGN TEACH PENDANT iPendant,2025-10-22,"$2,106.14||or Best Offer||Free International Shipping||Located in United States||Free returns||View similar active items||Sell one like this",mattexr ||98.8% positive (367),https://www.ebay.com/itm/388505577933?_skw=FANUC+robot&itmmeta=01KPCJXEMGPE5SNSQRTJCGJBMN&hash=item5a74bca9cd:g:fGcAAOSwAW1oPX8M&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xAbys3a9Ca%2FepseS55HRhlpko2yEzPBkBwtRVd31OLSCLEGAUJB62CH4E2Y3QNRzxALkjNkDFgFHN8jFcu4oIqSQSKn%2BTBlyaeTNERUvtnILEiSA4QMG4XeGWJBvthX5DgV6492RjsbJHJvAThz%2BA6IWH64Q06Cu2WHUir%2B8P7Dxo8PqBcDg3zUmy7RUgwN4gRIaKckhCSAE9x6kfjYwoKc92SQ3Ur8Cto7PC2on%2BPQRWAkP9kNtiqm2nODFu2swrAlraUgpyo1SfSv5RpZS3B%2FFMS%2F0MpjfNcdZdOpSO7TVA%3D%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/388505577933?_skw=FANUC+robot&itmmeta=01KPCJXEMGPE5SNSQRTJCGJBMN&hash=item5a74bca9cd:g:fGcAAOSwAW1oPX8M&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xAbys3a9Ca%2FepseS55HRhlpko2yEzPBkBwtRVd31OLSCLEGAUJB62CH4E2Y3QNRzxALkjNkDFgFHN8jFcu4oIqSQSKn%2BTBlyaeTNERUvtnILEiSA4QMG4XeGWJBvthX5DgV6492RjsbJHJvAThz%2BA6IWH64Q06Cu2WHUir%2B8P7Dxo8PqBcDg3zUmy7RUgwN4gRIaKckhCSAE9x6kfjYwoKc92SQ3Ur8Cto7PC2on%2BPQRWAkP9kNtiqm2nODFu2swrAlraUgpyo1SfSv5RpZS3B%2FFMS%2F0MpjfNcdZdOpSO7TVA%3D%3D%7Ctkp%3ABk9SR67q9ZKzZw
4,FANUC robot,FANUC A290-7324-T503 / A2907324T503 (USED),2026-03-16,"$6,099.37||Buy It Now||+$72.77 delivery||Located in Canada||View similar active items||Sell one like this",radwellcanada ||99% positive (603),https://www.ebay.com/itm/386961036420?_skw=FANUC+robot&itmmeta=01KPCJXEMG237SVP79W59QCQ5Y&hash=item5a18acd484:g:cX0AAeSwYFxpzoXd&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xCv%2BcTC9isDQcR8wglHyJdYmkciwOrGcrJxdqD3CT7QMQNfEGvHjhxYRGNNaOyUFjAcwMGIyU4f%2FkE3hvF%2B5jSpriSBg%2FNLgCmMTjk7eIw0VpWgDtZ8n9ikDz1WZiyioWH0NiD6b6ZaBnUR1%2Bs4MhfQurwkA%2BHZa1GFhcIPnVit7V8TyT7a5gyQQK2tBrNUJzFQA0GCI7CrFzL1Eb9B2%2F0S4cbKM98wezer%2FcnH7T1Ioz%2BwxKHsgs%2BPuOb2ES1gW40%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/386961036420?_skw=FANUC+robot&itmmeta=01KPCJXEMG237SVP79W59QCQ5Y&hash=item5a18acd484:g:cX0AAeSwYFxpzoXd&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xCv%2BcTC9isDQcR8wglHyJdYmkciwOrGcrJxdqD3CT7QMQNfEGvHjhxYRGNNaOyUFjAcwMGIyU4f%2FkE3hvF%2B5jSpriSBg%2FNLgCmMTjk7eIw0VpWgDtZ8n9ikDz1WZiyioWH0NiD6b6ZaBnUR1%2Bs4MhfQurwkA%2BHZa1GFhcIPnVit7V8TyT7a5gyQQK2tBrNUJzFQA0GCI7CrFzL1Eb9B2%2F0S4cbKM98wezer%2FcnH7T1Ioz%2BwxKHsgs%2BPuOb2ES1gW40%3D%7Ctkp%3ABk9SR67q9ZKzZw

## 3. Createting Column **sold_price_usd**

In [41]:
df["primary_container"].str.split(r"\|\|")

0                              [$4,999.95, or Best Offer, +$760.13 delivery, Located in United States, View similar active items, Sell one like this]
1                                      [$2,400.00, or Best Offer, +$87.00 delivery, Located in Israel, View similar active items, Sell one like this]
2                       [$15,000.00, or Best Offer, +$20.00 delivery, Located in Mexico, Free returns, View similar active items, Sell one like this]
3      [$2,106.14, or Best Offer, Free International Shipping, Located in United States, Free returns, View similar active items, Sell one like this]
4                                         [$6,099.37, Buy It Now, +$72.77 delivery, Located in Canada, View similar active items, Sell one like this]
                                                                            ...
726                                                              [$2,827.00, 39 bids, +$150.99 delivery, Located in Japan, View similar active items]
727                                               [$2,712.20, or Best Offer, +$269.19 delivery, Located in United Kingdom, View similar active items]
728                                                           [$2,960.11, Buy It Now, +$71.22 delivery, Located in Poland, View similar active items]
729                                        [$8,999.99, 1 bid, +$2,000.00 delivery, Located in United States, Free returns, View similar active items]
730                                                      [$3,538.52, or Best Offer, +$330.37 delivery, Located in Germany, View similar active items]
Name: primary_container, Length: 731, dtype: object

In [50]:
df["primary_container"].str.split(r"\|\|").str[0]

0       $4,999.95
1       $2,400.00
2      $15,000.00
3       $2,106.14
4       $6,099.37
          ...
726     $2,827.00
727     $2,712.20
728     $2,960.11
729     $8,999.99
730     $3,538.52
Name: primary_container, Length: 731, dtype: object

In [ ]:
df["primary_container"].str.split(r"\|\|").str[0].str.replace("$", "", regex=False).str.replace(",", "").astype(float)

0       4999.95
1       2400.00
2      15000.00
3       2106.14
4       6099.37
         ...
726     2827.00
727     2712.20
728     2960.11
729     8999.99
730     3538.52
Name: primary_container, Length: 731, dtype: float64

In [54]:
df["sold_price_usd"] = df["primary_container"].str.split(r"\|\|").str[0].str.replace("$", "", regex=False).str.replace(",", "").astype(float)

## 3. Createting Column :  **delivery_charge**

In [80]:
df["primary_container"].str.split(r"\|\|") \
    .apply(lambda list_text: next((i for i in list_text if "delivery" in i), None))

0        +$760.13 delivery
1         +$87.00 delivery
2         +$20.00 delivery
3                     None
4         +$72.77 delivery
              ...
726      +$150.99 delivery
727      +$269.19 delivery
728       +$71.22 delivery
729    +$2,000.00 delivery
730      +$330.37 delivery
Name: primary_container, Length: 731, dtype: object

In [85]:
df["primary_container"].str.split(r"\|\|") \
    .apply(lambda list_text: next((i for i in list_text if "delivery" in i), None)) \
    .str.replace(r"\$|\+|\,|delivery", "", regex=True).astype(float)

0       760.13
1        87.00
2        20.00
3          NaN
4        72.77
        ...
726     150.99
727     269.19
728      71.22
729    2000.00
730     330.37
Name: primary_container, Length: 731, dtype: float64

In [86]:
df["delivery_charge"] = df["primary_container"].str.split(r"\|\|") \
    .apply(lambda list_text: next((i for i in list_text if "delivery" in i), None)) \
    .str.replace(r"\$|\+|\,|delivery", "", regex=True).astype(float)

In [87]:
df.head()

,search_term,listing_title,sale_date,primary_container,secondary_container,product_link,product_image,sold_price_usd,delivery_info,delivery_charge
0,FANUC robot,GUARANTEED! FANUC LTD GMF ROBOTICS S-5 ARC MATE ROBOT SYSTEM A05B-1203-B251,2026-03-26,"$4,999.95||or Best Offer||+$760.13 delivery||Located in United States||View similar active items||Sell one like this",tcb3162 ||100% positive (34.9K),https://www.ebay.com/itm/326087574965?_skw=FANUC+robot&epid=4066690834&itmmeta=01KPCJXEMG5SHQVGDPYSDA5NA6&hash=item4bec5585b5:g:aOsAAOSw0qZmGZib&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xAWq8QhMLQsU8gg08bcq403RsqDXoYe7H%2FDwG051SnQX6BjZx0WxYDwUOz1X%2FwDOALNJTSzvWf3oZ8j4XO84knIAmjL9XZLiRDzcEsQtgP5zl00ZqvydbAlG00j6EXzC4PVWVE3bU5w%2BvDMMTPNiprYJ0uN5Ql6XZoy5MxfnTzsWAafkw1b053zpL6pyUw8lbycye1HVeTZVypwLDjWcDNYKL%2B3SePIt6tMNCmYKFicntFFsGNRaHcHut%2BeHfjzvnA%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/326087574965?_skw=FANUC+robot&epid=4066690834&itmmeta=01KPCJXEMG5SHQVGDPYSDA5NA6&hash=item4bec5585b5:g:aOsAAOSw0qZmGZib&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xAWq8QhMLQsU8gg08bcq403RsqDXoYe7H%2FDwG051SnQX6BjZx0WxYDwUOz1X%2FwDOALNJTSzvWf3oZ8j4XO84knIAmjL9XZLiRDzcEsQtgP5zl00ZqvydbAlG00j6EXzC4PVWVE3bU5w%2BvDMMTPNiprYJ0uN5Ql6XZoy5MxfnTzsWAafkw1b053zpL6pyUw8lbycye1HVeTZVypwLDjWcDNYKL%2B3SePIt6tMNCmYKFicntFFsGNRaHcHut%2BeHfjzvnA%3D%7Ctkp%3ABk9SR67q9ZKzZw,4999.95,+$760.13 delivery,760.13
1,FANUC robot,Fanuc A05B-2696-B001 CONTROL R-30iB Mini Plus for CRX-10iA/L Collaborative Robot,2025-08-28,"$2,400.00||or Best Offer||+$87.00 delivery||Located in Israel||View similar active items||Sell one like this",ysmetronics2010 ||99.5% positive (2.9K),https://www.ebay.com/itm/235882269777?_skw=FANUC+robot&itmmeta=01KPCJXEMGDR015Y9QQHHMX3QD&hash=item36ebadcc51:g:NDMAAOSwtlNnaXLm&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xBeTmmJKwqqUeyaIG08npIsPw%2BQ5cOet43SgDvdLVZo7UlsM3lX4tLGcw5cqwJPK0163QcT5Gdww4ggasAI7rA5%2B1vOLp5MnPZWMC%2Bj9A798weoDj%2FMW2FQnTPmpdaLliwIgfOIrFVizYXfdrHQ4LxLJfHSKOg4yA34xL0vH7VnBXa0VJZV6Y28kOiI8PT%2FBmus%2FWVDWpeR6CMErgoDQ5c28oCY%2BvdrsI5hNa6BmiFpwEXhZcq%2BXRy3KpoqlB9bWy4%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/235882269777?_skw=FANUC+robot&itmmeta=01KPCJXEMGDR015Y9QQHHMX3QD&hash=item36ebadcc51:g:NDMAAOSwtlNnaXLm&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xBeTmmJKwqqUeyaIG08npIsPw%2BQ5cOet43SgDvdLVZo7UlsM3lX4tLGcw5cqwJPK0163QcT5Gdww4ggasAI7rA5%2B1vOLp5MnPZWMC%2Bj9A798weoDj%2FMW2FQnTPmpdaLliwIgfOIrFVizYXfdrHQ4LxLJfHSKOg4yA34xL0vH7VnBXa0VJZV6Y28kOiI8PT%2FBmus%2FWVDWpeR6CMErgoDQ5c28oCY%2BvdrsI5hNa6BmiFpwEXhZcq%2BXRy3KpoqlB9bWy4%3D%7Ctkp%3ABk9SR67q9ZKzZw,2400.00,+$87.00 delivery,87.00
2,FANUC robot,FANUC R-30iB Plus 🤖 ROBOT LR MATE 200iD + A05B-2256-C103#EMH fully working,2026-03-21,"$15,000.00||or Best Offer||+$20.00 delivery||Located in Mexico||Free returns||View similar active items||Sell one like this",plccompany_mx ||100% positive (427),https://www.ebay.com/itm/136952732178?_skw=FANUC+robot&itmmeta=01KPCJXEMGWT5ZQ5B3SX3560RS&hash=item1fe304da12:g:qSYAAeSwpMhpaXWH&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xBsnbgeG0KdEsFRSar6BqDoD3ATpF10fFFgXRZaNlDdpwIRpeY9u9%2BHe75PvCfaDguXu%2BlbDRHkuB%2BjiEKWyzLNyxDdFimycBj6rpCSbwRrsmkAl6znHfxQFEg8g4WfZce8ysitTL%2BqTwuJA6vBWUX21XsrChJRV8VJ26akms4oTf6CnGqOLjjhxGx%2FxvyT7M2gdHntyRft4O3RYx9xZOhs04P6SijNxw6qpHVYFdaCrDiW7WhUuCHjD0HkPTPWXwivYFHKjP0e3lrTGnh%2BlzQfvzrRMnayvInETb2DcIukSQ%3D%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/136952732178?_skw=FANUC+robot&itmmeta=01KPCJXEMGWT5ZQ5B3SX3560RS&hash=item1fe304da12:g:qSYAAeSwpMhpaXWH&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xBsnbgeG0KdEsFRSar6BqDoD3ATpF10fFFgXRZaNlDdpwIRpeY9u9%2BHe75PvCfaDguXu%2BlbDRHkuB%2BjiEKWyzLNyxDdFimycBj6rpCSbwRrsmkAl6znHfxQFEg8g4WfZce8ysitTL%2BqTwuJA6vBWUX21XsrChJRV8VJ26akms4oTf6CnGqOLjjhxGx%2FxvyT7M2gdHntyRft4O3RYx9xZOhs04P6SijNxw6qpHVYFdaCrDiW7WhUuCHjD0HkPTPWXwivYFHKjP0e3lrTGnh%2BlzQfvzrRMnayvInETb2DcIukSQ%3D%3D%7Ctkp%3ABk9SR67q9ZKzZw,15000.00,+$20.00 delivery,20.00
3,FANUC robot,New FANUC A05B-2256-C101#EGN TEACH PENDANT iPendant,2025-10-22,"$2,106.14||or Best Offer||Free International Shipping||Located in United States||Free returns||View similar active items||Sell one like this",mattexr ||98.8% positive (367),https://www.ebay.com/itm/388505577933?_skw=FANUC+robot&itmmeta=01KPCJXEMGPE5SNSQRTJCGJBMN&hash=item5a74bca9cd:g:fGcAAOSwAW1oPX8M&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xAbys3a9Ca%2FepseS55HRhlpko2yEzPBkBwtRVd31OLSCLEGAUJB62CH4E2Y3QNRzxALkjNkDFgFHN8jFcu4oIqSQSKn%2BTBlyaeTNERUvtnILEiSA4QMG4XeGWJBvthX5DgV6492RjsbJHJvAThz%2BA6IWH64Q06Cu2WHUir%2B8P7Dxo8PqBcDg3zUmy7RUgwN4gRIaKckhCSAE9x6kfjYwoKc92SQ3Ur8Cto7PC2on%2BPQRWAkP9kNtiqm2nODFu2swrAlraUgpyo1SfSv5RpZS3B%2FFMS%2F0MpjfNcdZdOpSO7TVA%3D%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/388505577933?_skw=FANUC+robot&itmmeta=01KPCJXEMGPE5SNSQRTJCGJBMN&hash=item5a74bca9cd:g:fGcAAOSwAW1oPX8M&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xAbys3a9Ca%2FepseS55HRhlpko2yEzPBkBwtRVd31OLSCLEGAUJB62CH4E2Y3QNRzxALkjNkDFgFHN8jFcu4oIqSQSKn%2BTBlyaeTNERUvtnILEiSA4QMG4XeGWJBvthX5DgV6492RjsbJHJvAThz%2BA6IWH64Q06Cu2WHUir%2B8P7Dxo8PqBcDg3zUmy7RUgwN4gRIaKckhCSAE9x6kfjYwoKc92SQ3Ur8Cto7PC2on%2BPQRWAkP9kNtiqm2nODFu2swrAlraUgpyo1SfSv5RpZS3B%2FFMS%2F0MpjfNcdZdOpSO7TVA%3D%3D%7Ctkp%3ABk9SR67q9ZKzZw,2106.14,None,NaN
4,FANUC robot,FANUC A290-7324-T503 / A2907324T503 (USED),2026-03-16,"$6,099.37||Buy It Now||+$72.77 delivery||Located in Canada||View similar active items||Sell one like this",radwellcanada ||99% positive (603),https://www.ebay.com/itm/386961036420?_skw=FANUC+robot&itmmeta=01KPCJXEMG237SVP79W59QCQ5Y&hash=item5a18acd484:g:cX0AAeSwYFxpzoXd&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xCv%2BcTC9isDQcR8wglHyJdYmkciwOrGcrJxdqD3CT7QMQNfEGvHjhxYRGNNaOyUFjAcwMGIyU4f%2FkE3hvF%2B5jSpriSBg%2FNLgCmMTjk7eIw0VpWgDtZ8n9ikDz1WZiyioWH0NiD6b6ZaBnUR1%2Bs4MhfQurwkA%2BHZa1GFhcIPnVit7V8TyT7a5gyQQK2tBrNUJzFQA0GCI7CrFzL1Eb9B2%2F0S4cbKM98wezer%2FcnH7T1Ioz%2BwxKHsgs%2BPuOb2ES1gW40%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/386961036420?_skw=FANUC+robot&itmmeta=01KPCJXEMG237SVP79W59QCQ5Y&hash=item5a18acd484:g:cX0AAeSwYFxpzoXd&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xCv%2BcTC9isDQcR8wglHyJdYmkciwOrGcrJxdqD3CT7QMQNfEGvHjhxYRGNNaOyUFjAcwMGIyU4f%2FkE3hvF%2B5jSpriSBg%2FNLgCmMTjk7eIw0VpWgDtZ8n9ikDz1WZiyioWH0NiD6b6ZaBnUR1%2Bs4MhfQurwkA%2BHZa1GFhcIPnVit7V8TyT7a5gyQQK2tBrNUJzFQA0GCI7CrFzL1Eb9B2%2F0S4cbKM98wezer%2FcnH7T1Ioz%2BwxKHsgs%2BPuOb2ES1gW40%3D%7Ctkp%3ABk9SR67q9ZKzZw,6099.37,+$72.77 delivery,72.77

## 4. Creating Column :  **seller_location**

In [94]:
df["primary_container"].str.split(r"\|\|").apply(lambda l_in_list : [l for l in l_in_list if "Located" in l])

0       [Located in United States]
1              [Located in Israel]
2              [Located in Mexico]
3       [Located in United States]
4              [Located in Canada]
                  ...
726             [Located in Japan]
727    [Located in United Kingdom]
728            [Located in Poland]
729     [Located in United States]
730           [Located in Germany]
Name: primary_container, Length: 731, dtype: object

In [99]:
df["primary_container"].str.split(r"\|\|").apply(lambda l_in_list : next(l for l in l_in_list if "Located" in l)).str.replace("Located in", "").str.strip()

0       United States
1              Israel
2              Mexico
3       United States
4              Canada
            ...
726             Japan
727    United Kingdom
728            Poland
729     United States
730           Germany
Name: primary_container, Length: 731, dtype: object

In [100]:
df["seller_location"] = df["primary_container"].str.split(r"\|\|").apply(lambda l_in_list : next(l for l in l_in_list if "Located" in l)).str.replace("Located in", "").str.strip()

# 5. Creating Column : seller_name

In [106]:
df["secondary_container"].str.split(r'\|\|')

0                        [tcb3162 , 100% positive (34.9K)]
1                [ysmetronics2010 , 99.5% positive (2.9K)]
2                    [plccompany_mx , 100% positive (427)]
3                         [mattexr , 98.8% positive (367)]
4                     [radwellcanada , 99% positive (603)]
                              ...
726                 [urubei_japan , 98.3% positive (7.6K)]
727    [industrial_part_solutions , 99.8% positive (3.2K)]
728                 [a-z_automatyka , 99.5% positive (8K)]
729            [nevadasurplus-com , 100% positive (11.4K)]
730                      [habibu2005 , 100% positive (5K)]
Name: secondary_container, Length: 731, dtype: object

In [108]:
df["secondary_container"].str.split(r'\|\|').str[0]

0                        tcb3162
1                ysmetronics2010
2                  plccompany_mx
3                        mattexr
4                  radwellcanada
                  ...
726                 urubei_japan
727    industrial_part_solutions
728               a-z_automatyka
729            nevadasurplus-com
730                   habibu2005
Name: secondary_container, Length: 731, dtype: object

In [109]:
df["seller"] = df["secondary_container"].str.split(r'\|\|').str[0]

## 6. Creating Column **seller_review_percentage**

In [134]:
seller_reviews = df["secondary_container"].str.split(r'\|\|').str[-1].str.split(" ")
seller_reviews

0      [100%, positive, (34.9K)]
1      [99.5%, positive, (2.9K)]
2        [100%, positive, (427)]
3       [98.8%, positive, (367)]
4         [99%, positive, (603)]
                 ...
726    [98.3%, positive, (7.6K)]
727    [99.8%, positive, (3.2K)]
728      [99.5%, positive, (8K)]
729    [100%, positive, (11.4K)]
730       [100%, positive, (5K)]
Name: secondary_container, Length: 731, dtype: object

In [136]:
df["secondary_container"].str.split(r'\|\|').str[-1].str.split(" ").str[0]

0       100%
1      99.5%
2       100%
3      98.8%
4        99%
       ...
726    98.3%
727    99.8%
728    99.5%
729     100%
730     100%
Name: secondary_container, Length: 731, dtype: object

In [137]:
df["seller_review_percentag"] = df["secondary_container"].str.split(r'\|\|').str[-1].str.split(" ").str[0]

## 7. Creating Column **seller_review_type**

In [139]:
df["secondary_container"].str.split(r'\|\|').str[-1].str.split(" ").str[1]

0      positive
1      positive
2      positive
3      positive
4      positive
         ...
726    positive
727    positive
728    positive
729    positive
730    positive
Name: secondary_container, Length: 731, dtype: object

In [ ]:
df["seller_review_type"] = df["secondary_container"].str.split(r'\|\|').str[-1].str.split(" ").str[1]

## 8. Creating Column : **no_of_seller_reviews**

In [143]:
df["secondary_container"].str.split(r'\|\|').str[-1].str.split(" ").str[-1].replace(r"\(|\)", "", regex=True)

0      34.9K
1       2.9K
2        427
3        367
4        603
       ...
726     7.6K
727     3.2K
728       8K
729    11.4K
730       5K
Name: secondary_container, Length: 731, dtype: object

In [145]:
df["no_of_seller_reviews"] = df["secondary_container"].str.split(r'\|\|').str[-1].str.split(" ").str[-1].replace(r"\(|\)", "", regex=True)

## 9. Creating Column : **brand_name**

In [182]:
df["listing_title"]

0           GUARANTEED! FANUC LTD GMF ROBOTICS S-5 ARC MATE ROBOT SYSTEM A05B-1203-B251
1      Fanuc A05B-2696-B001 CONTROL R-30iB Mini Plus for CRX-10iA/L Collaborative Robot
2            FANUC R-30iB Plus 🤖 ROBOT LR MATE 200iD + A05B-2256-C103#EMH fully working
3                                   New FANUC A05B-2256-C101#EGN TEACH PENDANT iPendant
4                                            FANUC A290-7324-T503 / A2907324T503 (USED)
                                             ...
726     Universal Robots UR3 CB3 Collaborative Robot Arm + Teach Pendant & Cables Power
727         COMAU SMART-5 RACER  7-1.4 SAFE  ROBOT With 6 Arms REL 2.0 CR82225100 150kg
728                               HIRATA ARM BASE ARM BASE AR-S270AE-4-200 ARS270AE4200
729    New Seiko Epson G10-851C Cleanroom SCARA Robot Arm 10kg + RC700-A Controller TP1
730                  MILARA INCORPORATED SINGLE ARM ROBOT ATM-105-1-S-CE 6-0002-1353-SP
Name: listing_title, Length: 731, dtype: object

In [183]:
brand_list = ["FANUC", "ABB", "KUKA", "Yaskawa", "Universal Robots", "Kawasaki", "Epson", "Denso", "Mitsubishi", "Staubli", "Comau", "Nachi"]
brand_list

['FANUC',
 'ABB',
 'KUKA',
 'Yaskawa',
 'Universal Robots',
 'Kawasaki',
 'Epson',
 'Denso',
 'Mitsubishi',
 'Staubli',
 'Comau',
 'Nachi']

In [184]:
df["listing_title"][0]

'GUARANTEED! FANUC LTD GMF ROBOTICS S-5 ARC MATE ROBOT SYSTEM A05B-1203-B251 '

In [185]:
def search_brand(listing_title):
    brand_list = ["FANUC", "ABB", "KUKA", "Yaskawa", "Universal Robots",
                  "Kawasaki", "Epson", "Denso", "Mitsubishi",
                  "Staubli", "Comau", "Nachi"]

    if pd.isna(listing_title):  # handle missing values
        return None

    title = listing_title.upper()

    for brand in brand_list:
        if brand.upper() in title:
            return brand.upper()

    return None

In [186]:
df["listing_title"].apply(search_brand)

0                 FANUC
1                 FANUC
2                 FANUC
3                 FANUC
4                 FANUC
             ...
726    UNIVERSAL ROBOTS
727               COMAU
728                None
729               EPSON
730                None
Name: listing_title, Length: 731, dtype: object

In [ ]:
df["brand_name"] = df["listing_title"].apply(search_brand)

## 10. Creating Colum : **controller**

In [190]:
df["listing_title"]

0           GUARANTEED! FANUC LTD GMF ROBOTICS S-5 ARC MATE ROBOT SYSTEM A05B-1203-B251
1      Fanuc A05B-2696-B001 CONTROL R-30iB Mini Plus for CRX-10iA/L Collaborative Robot
2            FANUC R-30iB Plus 🤖 ROBOT LR MATE 200iD + A05B-2256-C103#EMH fully working
3                                   New FANUC A05B-2256-C101#EGN TEACH PENDANT iPendant
4                                            FANUC A290-7324-T503 / A2907324T503 (USED)
                                             ...
726     Universal Robots UR3 CB3 Collaborative Robot Arm + Teach Pendant & Cables Power
727         COMAU SMART-5 RACER  7-1.4 SAFE  ROBOT With 6 Arms REL 2.0 CR82225100 150kg
728                               HIRATA ARM BASE ARM BASE AR-S270AE-4-200 ARS270AE4200
729    New Seiko Epson G10-851C Cleanroom SCARA Robot Arm 10kg + RC700-A Controller TP1
730                  MILARA INCORPORATED SINGLE ARM ROBOT ATM-105-1-S-CE 6-0002-1353-SP
Name: listing_title, Length: 731, dtype: object

# Final Data

In [192]:
df.columns

Index(['search_term', 'listing_title', 'sale_date', 'primary_container',
       'secondary_container', 'product_link', 'product_image',
       'sold_price_usd', 'delivery_info', 'delivery_charge', 'seller_location',
       'seller', 'seller_review_percentag', 'no_of_seller_reviews',
       'brand_name'],
      dtype='object')

In [194]:
cleanded_df = df[['search_term', 'listing_title', 'brand_name', 'sold_price_usd', 'delivery_charge', 'sale_date', 'seller','seller_location', 'seller_review_percentag', 'no_of_seller_reviews', 'product_link', 'product_image'
       ]]

In [195]:
cleanded_df

,search_term,listing_title,brand_name,sold_price_usd,delivery_charge,sale_date,seller,seller_location,seller_review_percentag,no_of_seller_reviews,product_link,product_image
0,FANUC robot,GUARANTEED! FANUC LTD GMF ROBOTICS S-5 ARC MATE ROBOT SYSTEM A05B-1203-B251,FANUC,4999.95,760.13,2026-03-26,tcb3162,United States,100%,34.9K,https://www.ebay.com/itm/326087574965?_skw=FANUC+robot&epid=4066690834&itmmeta=01KPCJXEMG5SHQVGDPYSDA5NA6&hash=item4bec5585b5:g:aOsAAOSw0qZmGZib&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xAWq8QhMLQsU8gg08bcq403RsqDXoYe7H%2FDwG051SnQX6BjZx0WxYDwUOz1X%2FwDOALNJTSzvWf3oZ8j4XO84knIAmjL9XZLiRDzcEsQtgP5zl00ZqvydbAlG00j6EXzC4PVWVE3bU5w%2BvDMMTPNiprYJ0uN5Ql6XZoy5MxfnTzsWAafkw1b053zpL6pyUw8lbycye1HVeTZVypwLDjWcDNYKL%2B3SePIt6tMNCmYKFicntFFsGNRaHcHut%2BeHfjzvnA%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/326087574965?_skw=FANUC+robot&epid=4066690834&itmmeta=01KPCJXEMG5SHQVGDPYSDA5NA6&hash=item4bec5585b5:g:aOsAAOSw0qZmGZib&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xAWq8QhMLQsU8gg08bcq403RsqDXoYe7H%2FDwG051SnQX6BjZx0WxYDwUOz1X%2FwDOALNJTSzvWf3oZ8j4XO84knIAmjL9XZLiRDzcEsQtgP5zl00ZqvydbAlG00j6EXzC4PVWVE3bU5w%2BvDMMTPNiprYJ0uN5Ql6XZoy5MxfnTzsWAafkw1b053zpL6pyUw8lbycye1HVeTZVypwLDjWcDNYKL%2B3SePIt6tMNCmYKFicntFFsGNRaHcHut%2BeHfjzvnA%3D%7Ctkp%3ABk9SR67q9ZKzZw
1,FANUC robot,Fanuc A05B-2696-B001 CONTROL R-30iB Mini Plus for CRX-10iA/L Collaborative Robot,FANUC,2400.00,87.00,2025-08-28,ysmetronics2010,Israel,99.5%,2.9K,https://www.ebay.com/itm/235882269777?_skw=FANUC+robot&itmmeta=01KPCJXEMGDR015Y9QQHHMX3QD&hash=item36ebadcc51:g:NDMAAOSwtlNnaXLm&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xBeTmmJKwqqUeyaIG08npIsPw%2BQ5cOet43SgDvdLVZo7UlsM3lX4tLGcw5cqwJPK0163QcT5Gdww4ggasAI7rA5%2B1vOLp5MnPZWMC%2Bj9A798weoDj%2FMW2FQnTPmpdaLliwIgfOIrFVizYXfdrHQ4LxLJfHSKOg4yA34xL0vH7VnBXa0VJZV6Y28kOiI8PT%2FBmus%2FWVDWpeR6CMErgoDQ5c28oCY%2BvdrsI5hNa6BmiFpwEXhZcq%2BXRy3KpoqlB9bWy4%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/235882269777?_skw=FANUC+robot&itmmeta=01KPCJXEMGDR015Y9QQHHMX3QD&hash=item36ebadcc51:g:NDMAAOSwtlNnaXLm&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xBeTmmJKwqqUeyaIG08npIsPw%2BQ5cOet43SgDvdLVZo7UlsM3lX4tLGcw5cqwJPK0163QcT5Gdww4ggasAI7rA5%2B1vOLp5MnPZWMC%2Bj9A798weoDj%2FMW2FQnTPmpdaLliwIgfOIrFVizYXfdrHQ4LxLJfHSKOg4yA34xL0vH7VnBXa0VJZV6Y28kOiI8PT%2FBmus%2FWVDWpeR6CMErgoDQ5c28oCY%2BvdrsI5hNa6BmiFpwEXhZcq%2BXRy3KpoqlB9bWy4%3D%7Ctkp%3ABk9SR67q9ZKzZw
2,FANUC robot,FANUC R-30iB Plus 🤖 ROBOT LR MATE 200iD + A05B-2256-C103#EMH fully working,FANUC,15000.00,20.00,2026-03-21,plccompany_mx,Mexico,100%,427,https://www.ebay.com/itm/136952732178?_skw=FANUC+robot&itmmeta=01KPCJXEMGWT5ZQ5B3SX3560RS&hash=item1fe304da12:g:qSYAAeSwpMhpaXWH&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xBsnbgeG0KdEsFRSar6BqDoD3ATpF10fFFgXRZaNlDdpwIRpeY9u9%2BHe75PvCfaDguXu%2BlbDRHkuB%2BjiEKWyzLNyxDdFimycBj6rpCSbwRrsmkAl6znHfxQFEg8g4WfZce8ysitTL%2BqTwuJA6vBWUX21XsrChJRV8VJ26akms4oTf6CnGqOLjjhxGx%2FxvyT7M2gdHntyRft4O3RYx9xZOhs04P6SijNxw6qpHVYFdaCrDiW7WhUuCHjD0HkPTPWXwivYFHKjP0e3lrTGnh%2BlzQfvzrRMnayvInETb2DcIukSQ%3D%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/136952732178?_skw=FANUC+robot&itmmeta=01KPCJXEMGWT5ZQ5B3SX3560RS&hash=item1fe304da12:g:qSYAAeSwpMhpaXWH&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xBsnbgeG0KdEsFRSar6BqDoD3ATpF10fFFgXRZaNlDdpwIRpeY9u9%2BHe75PvCfaDguXu%2BlbDRHkuB%2BjiEKWyzLNyxDdFimycBj6rpCSbwRrsmkAl6znHfxQFEg8g4WfZce8ysitTL%2BqTwuJA6vBWUX21XsrChJRV8VJ26akms4oTf6CnGqOLjjhxGx%2FxvyT7M2gdHntyRft4O3RYx9xZOhs04P6SijNxw6qpHVYFdaCrDiW7WhUuCHjD0HkPTPWXwivYFHKjP0e3lrTGnh%2BlzQfvzrRMnayvInETb2DcIukSQ%3D%3D%7Ctkp%3ABk9SR67q9ZKzZw
3,FANUC robot,New FANUC A05B-2256-C101#EGN TEACH PENDANT iPendant,FANUC,2106.14,NaN,2025-10-22,mattexr,United States,98.8%,367,https://www.ebay.com/itm/388505577933?_skw=FANUC+robot&itmmeta=01KPCJXEMGPE5SNSQRTJCGJBMN&hash=item5a74bca9cd:g:fGcAAOSwAW1oPX8M&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xAbys3a9Ca%2FepseS55HRhlpko2yEzPBkBwtRVd31OLSCLEGAUJB62CH4E2Y3QNRzxALkjNkDFgFHN8jFcu4oIqSQSKn%2BTBlyaeTNERUvtnILEiSA4QMG4XeGWJBvthX5DgV6492RjsbJHJvAThz%2BA6IWH64Q06Cu2WHUir%2B8P7Dxo8PqBcDg3zUmy7RUgwN4gRIaKckhCSAE9x6kfjYwoKc92SQ3Ur8Cto7PC2on%2BPQRWAkP9kNtiqm2nODFu2swrAlraUgpyo1SfSv5RpZS3B%2FFMS%2F0MpjfNcdZdOpSO7TVA%3D%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/388505577933?_skw=FANUC+robot&itmmeta=01KPCJXEMGPE5SNSQRTJCGJBMN&hash=item5a74bca9cd:g:fGcAAOSwAW1oPX8M&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xAbys3a9Ca%2FepseS55HRhlpko2yEzPBkBwtRVd31OLSCLEGAUJB62CH4E2Y3QNRzxALkjNkDFgFHN8jFcu4oIqSQSKn%2BTBlyaeTNERUvtnILEiSA4QMG4XeGWJBvthX5DgV6492RjsbJHJvAThz%2BA6IWH64Q06Cu2WHUir%2B8P7Dxo8PqBcDg3zUmy7RUgwN4gRIaKckhCSAE9x6kfjYwoKc92SQ3Ur8Cto7PC2on%2BPQRWAkP9kNtiqm2nODFu2swrAlraUgpyo1SfSv5RpZS3B%2FFMS%2F0MpjfNcdZdOpSO7TVA%3D%3D%7Ctkp%3ABk9SR67q9ZKzZw
4,FANUC robot,FANUC A290-7324-T503 / A2907324T503 (USED),FANUC,6099.37,72.77,2026-03-16,radwellcanada,Canada,99%,603,https://www.ebay.com/itm/386961036420?_skw=FANUC+robot&itmmeta=01KPCJXEMG237SVP79W59QCQ5Y&hash=item5a18acd484:g:cX0AAeSwYFxpzoXd&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xCv%2BcTC9isDQcR8wglHyJdYmkciwOrGcrJxdqD3CT7QMQNfEGvHjhxYRGNNaOyUFjAcwMGIyU4f%2FkE3hvF%2B5jSpriSBg%2FNLgCmMTjk7eIw0VpWgDtZ8n9ikDz1WZiyioWH0NiD6b6ZaBnUR1%2Bs4MhfQurwkA%2BHZa1GFhcIPnVit7V8TyT7a5gyQQK2tBrNUJzFQA0GCI7CrFzL1Eb9B2%2F0S4cbKM98wezer%2FcnH7T1Ioz%2BwxKHsgs%2BPuOb2ES1gW40%3D%7Ctkp%3ABk9SR67q9ZKzZw,https://www.ebay.com/itm/386961036420?_skw=FANUC+robot&itmmeta=01KPCJXEMG237SVP79W59QCQ5Y&hash=item5a18acd484:g:cX0AAeSwYFxpzoXd&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xCv%2BcTC9isDQcR8wglHyJdYmkciwOrGcrJxdqD3CT7QMQNfEGvHjhxYRGNNaOyUFjAcwMGIyU4f%2FkE3hvF%2B5jSpriSBg%2FNLgCmMTjk7eIw0VpWgDtZ8n9ikDz1WZiyioWH0NiD6b6ZaBnUR1%2Bs4MhfQurwkA%2BHZa1GFhcIPnVit7V8TyT7a5gyQQK2tBrNUJzFQA0GCI7CrFzL1Eb9B2%2F0S4cbKM98wezer%2FcnH7T1Ioz%2BwxKHsgs%2BPuOb2ES1gW40%3D%7Ctkp%3ABk9SR67q9ZKzZw
...,...,...,...,...,...,...,...,...,...,...,...,...
726,Nachi robot arm,Universal Robots UR3 CB3 Collaborative Robot Arm + Teach Pendant & Cables Power,UNIVERSAL ROBOTS,2827.00,150.99,2026-03-17,urubei_japan,Japan,98.3%,7.6K,https://www.ebay.com/itm/117079436945?_skw=Nachi+robot+arm&itmmeta=01KPCN5R3J78HXFX5DPGCPQZA1&hash=item1b427a6e91:g:7LcAAeSw--VpdIM6&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xB8awoKRwZaqaDPQ7L%2FCRHOZTbbkP2n2hixbsq8a9t5Ccajk0z3%2FGSAZN%2FYL6ZnOvuh%2BEYJCGqGR1YkXRatqDDlHwFhFXe%2FZdpIfcrNQuEQwY4THYdWZnAKA4LZKv%2BjAm%2FVx0ulJUiSRSsZBWrRsgtXV2Uqxhzwrh25FsuwCNslAj1i1R4r3%2BFp1miVwfr3qj7S9kBrZiHnLPsJqcemE%2B459C%2BA7OjhtBBjNNPL4%2Bs9nQgpt9LwgEj0SZWwJO0BHyU%3D%7Ctkp%3ABk9SR_SBl5WzZw,https://www.ebay.com/itm/117079436945?_skw=Nachi+robot+arm&itmmeta=01KPCN5R3J78HXFX5DPGCPQZA1&hash=item1b427a6e91:g:7LcAAeSw--VpdIM6&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xB8awoKRwZaqaDPQ7L%2FCRHOZTbbkP2n2hixbsq8a9t5Ccajk0z3%2FGSAZN%2FYL6ZnOvuh%2BEYJCGqGR1YkXRatqDDlHwFhFXe%2FZdpIfcrNQuEQwY4THYdWZnAKA4LZKv%2BjAm%2FVx0ulJUiSRSsZBWrRsgtXV2Uqxhzwrh25FsuwCNslAj1i1R4r3%2BFp1miVwfr3qj7S9kBrZiHnLPsJqcemE%2B459C%2BA7OjhtBBjNNPL4%2Bs9nQgpt9LwgEj0SZWwJO0BHyU%3D%7Ctkp%3ABk9SR_SBl5WzZw
727,Nachi robot arm,COMAU SMART-5 RACER 7-1.4 SAFE ROBOT With 6 Arms REL 2.0 CR82225100 150kg,COMAU,2712.20,269.19,2025-09-05,industrial_part_solutions,United Kingdom,99.8%,3.2K,https://www.ebay.com/itm/375143866340?_skw=Nachi+robot+arm&itmmeta=01KPCN5R3JT5D9KH4RAJ3FNKY6&hash=item5758511fe4:g:b3IAAOSwcNplids6&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xCpxgOJa5qJYf%2FjDB0L2Hx0U%2B3w5f%2BKEEImFtXpZfZl1%2BAjK7W10Gn9AlC7rqK3sYqYfyru79QHhAdr3IV3eMXDdNwidKayyLnegvq9SW8I5QEI%2F%2BrTGxoOZsnnm7X1CifnEMQ5fHmfPH%2FwV5J10%2B7kdA1mP2R4laZ7vHcByc21Xpb1mXLgBCTN%2FZeAG6ixeOG4aB%2BHjyceElrBTaeQo0xsO3W%2BDFdh3NGoefcKs443Wle0xBbh58eIQrjdDG3h%2B%2Bs%3D%7Ctkp%3ABk9SR_SBl5WzZw,https://www.ebay.com/itm/375143866340?_skw=Nachi+robot+arm&itmmeta=01KPCN5R3JT5D9KH4RAJ3FNKY6&hash=item5758511fe4:g:b3IAAOSwcNplids6&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xCpxgOJa5qJYf%2FjDB0L2Hx0U%2B3w5f%2BKEEImFtXpZfZl1%2BAjK7W10Gn9AlC7rqK3sYqYfyru79QHhAdr3IV3eMXDdNwidKayyLnegvq9SW8I5QEI%2F%2BrTGxoOZsnnm7X1CifnEMQ5fHmfPH%2FwV5J10%2B7kdA1mP2R4laZ7vHcByc21Xpb1mXLgBCTN%2FZeAG6ixeOG4aB%2BHjyceElrBTaeQo0xsO3W%2BDFdh3NGoefcKs443Wle0xBbh58eIQrjdDG3h%2B%2Bs%3D%7Ctkp%3ABk9SR_SBl5WzZw
728,Nachi robot arm,HIRATA ARM BASE ARM BASE AR-S270AE-4-200 ARS270AE4200,None,2960.11,71.22,2026-01-22,a-z_automatyka,Poland,99.5%,8K,https://www.ebay.com/itm/326872817583?_skw=Nachi+robot+arm&itmmeta=01KPCN5R3JR9VESCK5AB83FYTE&hash=item4c1b235faf:g:9pEAAOSw0TBcRuNH&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xDVFQFu1FOfkyUkIYOpuY66js0c1RBNKEwlrY%2Foa2BtJtBK%2B7zELWnfPOeSVQFmM2w%2BvNFKf%2BcEave8eClrUVYbN%2FTQJEeatEs808sbdSQXMc7dMZphXYRYgKom4Mse%2BJqytHVcI2xOvseY7RIsJgeLIlzJ2mcXb2eOs8WGogti3JkwCOkjMjpfj7GDa3G5tm8r%2Bu6Vcyv%2B27dmq5PESajsvR%2F3oErajWC7HlybygW9aul7rhgtRtZE5VJdH4qPzhAopLburqZrKJgt45L%2BycHsMNzLCmxnX87ryIx5dfQV4w%3D%3D%7Ctkp%3ABk9SR_SBl5WzZw,https://www.ebay.com/itm/326872817583?_skw=Nachi+robot+arm&itmmeta=01KPCN5R3JR9VESCK5AB83FYTE&hash=item4c1b235faf:g:9pEAAOSw0TBcRuNH&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xDVFQFu1FOfkyUkIYOpuY66js0c1RBNKEwlrY%2Foa2BtJtBK%2B7zELWnfPOeSVQFmM2w%2BvNFKf%2BcEave8eClrUVYbN%2FTQJEeatEs808sbdSQXMc7dMZphXYRYgKom4Mse%2BJqytHVcI2xOvseY7RIsJgeLIlzJ2mcXb2eOs8WGogti3JkwCOkjMjpfj7GDa3G5tm8r%2Bu6Vcyv%2B27dmq5PESajsvR%2F3oErajWC7HlybygW9aul7rhgtRtZE5VJdH4qPzhAopLburqZrKJgt45L%2BycHsMNzLCmxnX87ryIx5dfQV4w%3D%3D%7Ctkp%3ABk9SR_SBl5WzZw
729,Nachi robot arm,New Seiko Epson G10-851C Cleanroom SCARA Robot Arm 10kg + RC700-A Controller TP1,EPSON,8999.99,2000.00,2026-01-29,nevadasurplus-com,United States,100%,11.4K,https://www.ebay.com/itm/116995915910?_skw=Nachi+robot+arm&itmmeta=01KPCN5R3J08Z06V9NXM98WZ4B&hash=item1b3d800086:g:kh4AAOSw-UNlg1d7&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xBm6eUZcSqQIU%2FdsF%2BZekOq451os2LCvo47PStxb0Hyr5jgsIiRQyNEQSDf0XDx4fQj1FhouJYmIjz2uaCLzxRJJZ7XkMx2PUxBYQcmpe5bRPrdekhDoU0xVYdksC35NOgL8pkQz%2BFjT4X8sGHjdWiWToMrTfIlErhgrAwbMangVEx%2FDUHFCvibJYfBF9xkHx7rib36b27tEGJB3gFwnbVZp1eLw89%2FB%2Fsr2DkD8DAtyPHEfBX9fKFU4UEgXs0Vcao%3D%7Ctkp%3ABk9SR_SBl5WzZw,https://www.ebay.com/itm/116995915910?_skw=Nachi+robot+arm&itmmeta=01KPCN5R3J08Z06V9NXM98WZ4B&hash=item1b3d800086:g:kh4AAOSw-UNlg1d7&itmprp=enc%3AAQALAAAA0GfYFPkwiKCW4ZNSs2u11xBm6eUZcSqQIU%2FdsF%2BZekOq451os2LCvo47PStxb0Hyr5jgsIiRQyNEQSDf0XDx4fQj1FhouJYmIjz2uaCLzxRJJZ7XkMx2PUxBYQcmpe5bRPrdekhDoU0xVYdksC35NOgL8pkQz%2BFjT4X8sGHjdWiWToMrTfIlErhgrAwbMangVEx%2FDUHFCvibJYfBF9xkHx7rib36b27tEGJB3gFwnbVZp1eLw89%2FB%2Fsr2DkD8DAtyPHEfBX9fKFU4UEgXs0Vcao%3D%7Ctkp%3ABk9SR_SBl5WzZw
730,Nachi robot arm,MILARA INCORPORATED SINGLE ARM ROBOT ATM-105-1-S-CE 6-0002-1353-SP,None,3538.52,330.37,2026-03-06,habibu2005,Germany,100%,5K,https://www.ebay.com/itm/257393241318?_skw=Nachi+robot+arm&itmmeta=01KPCN5R3K4MH2DWATSD19ACVP&hash=item3bedd52ce6:g:S18AAeSwQmppqo73&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xAYMUnKzedGgsogaoQIXrohG3YpSAI6hLsMwmxBTQ%2B93TfPIWcfxSLTAGsOzro%2FC9BQoFYu34D2ak73WPqvmIOC1DFA%2FzEbOko%2FmAlBzhjlpWFrofUAxUhzjfbRbssqA4%2Ffjb7qSo%2FjBuJ6JnwowIzAcNt7UxHK9m2uPN6PLrwZPtUx9jRbNrxZlpQTc42aM9gA69kNu30HHbqtk9b8Us%2Fu8Szp2texivXVEpoC9KuHbffaCCPcTPLUCsUaPr0DgLbPy5REiYC%2BmjI4oqyzCJ%2FFCNavZl%2FCTWI%2BhWnGzq01aA%3D%3D%7Ctkp%3ABk9SR_SBl5WzZw,https://www.ebay.com/itm/257393241318?_skw=Nachi+robot+arm&itmmeta=01KPCN5R3K4MH2DWATSD19ACVP&hash=item3bedd52ce6:g:S18AAeSwQmppqo73&itmprp=enc%3AAQALAAAA8GfYFPkwiKCW4ZNSs2u11xAYMUnKzedGgsogaoQIXrohG3YpSAI6hLsMwmxBTQ%2B93TfPIWcfxSLTAGsOzro%2FC9BQoFYu34D2ak73WPqvmIOC1DFA%2FzEbOko%2FmAlBzhjlpWFrofUAxUhzjfbRbssqA4%2Ffjb7qSo%2FjBuJ6JnwowIzAcNt7UxHK9m2uPN6PLrwZPtUx9jRbNrxZlpQTc42aM9gA69kNu30HHbqtk9b8Us%2Fu8Szp2texivXVEpoC9KuHbffaCCPcTPLUCsUaPr0DgLbPy5REiYC%2BmjI4oqyzCJ%2FFCNavZl%2FCTWI%2BhWnGzq01aA%3D%3D%7Ctkp%3ABk9SR_SBl5WzZw

# Saving the File

In [ ]:
cleanded_df.to_excel("01_cleaned_sold_robots_data.xlsx", sheet_name="sold_robots", index=False)